export {
  addUserActivity,
  createAnnouncement,
  createGroup,
  createHostelListing,
  createStudentListing,
  createNote,
  createQuestion,
  createStory,
  createTutorialListing,
  updateHostelListing,
  updateNote,
  updateQuestion,
  updateStudentListing,
  updateStory,
  deleteBookmark,
  ensureCurrentUserProfile as ensureUserProfile,
  fetchAnnouncements,
  fetchAnnouncementsPage,
  fetchBookmarks,
  fetchConversations,
  fetchFormulas,
  fetchGroups,
  fetchUserGroups,
  countUserUploads,
  fetchUserDocuments,
  fetchHostels,
  fetchHostelsPage,
  fetchNotes,
  fetchNotesPage,
  fetchNotifications,
  fetchNotificationsPage,
  fetchQuestions,
  fetchQuestionsPage,
  fetchRecord,
  fetchStories,
  fetchStoriesPage,
  fetchStudentListings,
  fetchStudentListingsPage,
  fetchStudyMaterials,
  fetchStudyMaterialsPage,
  fetchTutorialPurchases,
  fetchTutorials,
  fetchTutorialsPage,
  fetchAllTutorialPurchases,
  fetchUserActivity,
  getCurrentUserProfile as getUserProfile,
  groupPaths,
  markNotificationRead,
  notifyInactiveUsers,
  saveBookmark,
  syncCurrentUserProfile as saveUserProfile,
  conversationPaths,
  createFormulaBookmark,
  deleteStory,
  deleteStudentListing,
  deleteHostelListing,
  deleteNote,
  deleteQuestion,
  toggleStoryLike,
  addStoryComment,
  fetchStoryComments,
  incrementStoryView,
  blockUser,
  unblockUser,
  recordDailyStreak,
  fetchDailyStreak,
  
} from '../src/shared/services/firestore';

export {
  createPromoSpotlight,
  deletePromoSpotlight,
  fetchPromoSpotlightsForAdmin,
  fetchPromoSpotlightStats,
  updatePromoSpotlight,
} from '../src/shared/services/promoSpotlightService';
