export const CHALLENGE_DIFFICULTIES = ['Easy', 'Medium', 'Hard'];

// ──────────────────────────────────────────────
//  NEW CATEGORY SYSTEM — Personalized & Engaging
// ──────────────────────────────────────────────

/**
 * Challenge categories designed for personalization.
 * Each user sees categories relevant to their profile
 * (studentType, department, faculty, level).
 *
 * The old department+level categories (e.g. "100L Science")
 * are now behind-the-scenes filters rather than visible cards.
 */

/**
 * Returns categories ordered by personal relevance for the given user profile.
 * - University students -> department, level, faculty challenges first
 * - Everyone -> daily, weekly, speed quiz, general
 */


export const CHALLENGE_CATEGORIES = [
  {
    id: 'daily',
    title: 'Daily Challenge',
    subtitle: 'New questions every day',
    icon: 'calendar-outline',
    tone: '#6366F1',
    difficulty: 'Mixed',
    questionCount: 1000,
  },
  {
    id: 'weekly',
    title: 'Weekly Quiz',
    subtitle: 'Test your weekly knowledge',
    icon: 'trophy-outline',
    tone: '#F97316',
    difficulty: 'Mixed',
    questionCount: 500,
  },
  {
    id: 'department',
    title: 'Department',
    subtitle: 'Your course materials',
    icon: 'library-outline',
    tone: '#10B981',
    difficulty: 'Mixed',
    questionCount: 1500,
  },
  {
    id: 'level',
    title: 'Level',
    subtitle: 'Your academic level',
    icon: 'layers-outline',
    tone: '#9333EA',
    difficulty: 'Mixed',
    questionCount: 1200,
  },
  {
    id: 'faculty',
    title: 'Faculty',
    subtitle: 'Cross-department knowledge',
    icon: 'business-outline',
    tone: '#EC4899',
    difficulty: 'Mixed',
    questionCount: 800,
  },
  {
    id: 'speed-quiz',
    title: 'Speed Quiz',
    subtitle: 'Answer fast, score big',
    icon: 'timer-outline',
    tone: '#EF4444',
    difficulty: 'Mixed',
    questionCount: 600,
  },
  {
    id: 'aptitude',
    title: 'Aptitude',
    subtitle: 'Logic & reasoning',
    icon: 'bulb-outline',
    tone: '#14B8A6',
    difficulty: 'Mixed',
    questionCount: 700,
  },
  {
    id: 'general-knowledge',
    title: 'General Knowledge',
    subtitle: 'Current affairs & GK',
    icon: 'globe-outline',
    tone: '#F59E0B',
    difficulty: 'Mixed',
    questionCount: 900,
  },
];

export const getRecommendedCategories = (profile = {}) => {
  const priority = ['daily', 'department', 'level', 'faculty', 'weekly', 'speed-quiz', 'aptitude', 'general-knowledge'];
  return priority.map((id) => CHALLENGE_CATEGORIES.find((c) => c.id === id)).filter(Boolean);
};

export const CHALLENGE_ACHIEVEMENTS = [
  { id: 'first-challenge', title: 'First Challenge', icon: 'flag-outline', target: 1, metric: 'attempts' },
  { id: 'seven-day-streak', title: '7 Day Streak', icon: 'flame-outline', target: 7, metric: 'currentStreak' },
  { id: 'thirty-day-streak', title: '30 Day Streak', icon: 'bonfire-outline', target: 30, metric: 'currentStreak' },
  { id: 'hundred-questions', title: '100 Questions', icon: 'checkmark-done-outline', target: 100, metric: 'questionsAnswered' },
  { id: 'five-hundred-questions', title: '500 Questions', icon: 'layers-outline', target: 500, metric: 'questionsAnswered' },
  { id: 'thousand-questions', title: '1,000 Questions', icon: 'trophy-outline', target: 1000, metric: 'questionsAnswered' },
  { id: 'daily-dedicated', title: 'Daily Dedicated', icon: 'flame-outline', target: 30, metric: 'dailyCorrect' },
  { id: 'department-expert', title: 'Department Expert', icon: 'library-outline', target: 50, metric: 'departmentCorrect' },
  { id: 'aptitude-ace', title: 'Aptitude Ace', icon: 'bulb-outline', target: 30, metric: 'aptitudeCorrect' },
  { id: 'speed-demon', title: 'Speed Demon', icon: 'timer-outline', target: 20, metric: 'speed-quizCorrect' },
  { id: 'weekly-warrior', title: 'Weekly Warrior', icon: 'trophy-outline', target: 10, metric: 'weeklyCorrect' },
  { id: 'top-performer', title: 'Top Performer', icon: 'trophy-outline', target: 5000, metric: 'xp' },
  { id: 'early-bird', title: 'Early Bird', icon: 'sunny-outline', target: 3, metric: 'earlySessions' },
  { id: 'night-owl', title: 'Night Owl', icon: 'moon-outline', target: 3, metric: 'nightSessions' },
  { id: 'perfect-score', title: 'Perfect Score', icon: 'star-outline', target: 1, metric: 'perfectScores' },
];

export const FALLBACK_QUESTIONS = [
  // ─── DAILY: Mixed Subjects ────────────────────────────────
  {
    id: 'daily-phys-1',
    category: 'daily',
    subject: 'Physics',
    difficulty: 'Medium',
    prompt: 'What is the SI unit of force?',
    answers: ['Joule', 'Newton', 'Watt', 'Pascal'],
    correctIndex: 1,
    explanation: 'Force is measured in newtons (N).',
  },
  {
    id: 'daily-chem-1',
    category: 'daily',
    subject: 'Chemistry',
    difficulty: 'Easy',
    prompt: 'Which particle has a negative charge?',
    answers: ['Proton', 'Neutron', 'Electron', 'Nucleus'],
    correctIndex: 2,
    explanation: 'Electrons carry negative charge.',
  },
  {
    id: 'daily-bio-1',
    category: 'daily',
    subject: 'Biology',
    difficulty: 'Easy',
    prompt: 'The basic unit of life is the:',
    answers: ['Tissue', 'Organ', 'Cell', 'System'],
    correctIndex: 2,
    explanation: 'Cells are the basic structural and functional units of life.',
  },
  {
    id: 'daily-cell-1',
    category: 'daily',
    subject: 'General Biology',
    difficulty: 'Easy',
    prompt: 'The basic unit of life is the:',
    answers: ['Atom', 'Cell', 'Tissue', 'Organ'],
    correctIndex: 1,
    explanation: 'The cell is the basic structural and functional unit of all living organisms.',
  },
  {
    id: 'daily-maths-1',
    category: 'daily',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 25% of 80?',
    answers: ['15', '20', '25', '30'],
    correctIndex: 1,
    explanation: '25% of 80 = (25/100) × 80 = 20.',
  },
  {
    id: 'daily-maths-2',
    category: 'daily',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the area of a circle with radius 7cm? (Use π = 22/7)',
    answers: ['144 cm²', '154 cm²', '164 cm²', '174 cm²'],
    correctIndex: 1,
    explanation: 'Area = πr² = (22/7) × 7 × 7 = 154 cm².',
  },
  {
    id: 'daily-eng-1',
    category: 'daily',
    subject: 'English',
    difficulty: 'Easy',
    prompt: 'Which word is a noun?',
    answers: ['Quickly', 'Beautiful', 'Happiness', 'Run'],
    correctIndex: 2,
    explanation: '"Happiness" is a noun (a thing/feeling), while the others are adverb, adjective, and verb.',
  },
  {
    id: 'daily-eng-2',
    category: 'daily',
    subject: 'English',
    difficulty: 'Medium',
    prompt: 'What is the past tense of "sing"?',
    answers: ['Sang', 'Sung', 'Singed', 'Song'],
    correctIndex: 0,
    explanation: 'The simple past tense of "sing" is "sang".',
  },
  {
    id: 'daily-phys-2',
    category: 'daily',
    subject: 'Physics',
    difficulty: 'Easy',
    prompt: 'What is the unit of electric current?',
    answers: ['Volt', 'Ampere', 'Ohm', 'Watt'],
    correctIndex: 1,
    explanation: 'Electric current is measured in amperes (amps).',
  },
  {
    id: 'daily-chem-2',
    category: 'daily',
    subject: 'Chemistry',
    difficulty: 'Medium',
    prompt: 'Which element has the symbol "Fe"?',
    answers: ['Francium', 'Iron', 'Fluorine', 'Fermium'],
    correctIndex: 1,
    explanation: 'Fe is the chemical symbol for Iron, from the Latin "ferrum".',
  },
  {
    id: 'daily-bio-2',
    category: 'daily',
    subject: 'Biology',
    difficulty: 'Medium',
    prompt: 'Which part of the plant conducts photosynthesis?',
    answers: ['Root', 'Stem', 'Leaf', 'Flower'],
    correctIndex: 2,
    explanation: 'Leaves contain chloroplasts that perform photosynthesis.',
  },
  {
    id: 'daily-his-1',
    category: 'daily',
    subject: 'History',
    difficulty: 'Easy',
    prompt: 'In which year did Nigeria gain independence?',
    answers: ['1957', '1960', '1963', '1970'],
    correctIndex: 1,
    explanation: 'Nigeria gained independence from Britain on October 1, 1960.',
  },
  {
    id: 'daily-his-2',
    category: 'daily',
    subject: 'History',
    difficulty: 'Medium',
    prompt: 'Who was the first Prime Minister of Nigeria?',
    answers: ['Nnamdi Azikiwe', 'Abubakar Tafawa Balewa', 'Obafemi Awolowo', 'Ahmadu Bello'],
    correctIndex: 1,
    explanation: 'Sir Abubakar Tafawa Balewa served as Nigeria\'s first Prime Minister from 1960 to 1966.',
  },
  {
    id: 'daily-geo-1',
    category: 'daily',
    subject: 'Geography',
    difficulty: 'Easy',
    prompt: 'Which continent has the largest population?',
    answers: ['Africa', 'Europe', 'Asia', 'North America'],
    correctIndex: 2,
    explanation: 'Asia is the most populous continent, home to over 4.6 billion people.',
  },
  {
    id: 'daily-geo-2',
    category: 'daily',
    subject: 'Geography',
    difficulty: 'Medium',
    prompt: 'What is the smallest country in the world by area?',
    answers: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctIndex: 1,
    explanation: 'Vatican City is the smallest country, with an area of about 0.44 km².',
  },
  {
    id: 'daily-sport-1',
    category: 'daily',
    subject: 'Sports',
    difficulty: 'Easy',
    prompt: 'How many players are on a football (soccer) team?',
    answers: ['9', '10', '11', '12'],
    correctIndex: 2,
    explanation: 'A standard football team has 11 players on the field.',
  },
  {
    id: 'daily-sport-2',
    category: 'daily',
    subject: 'Sports',
    difficulty: 'Medium',
    prompt: 'Which country has won the most FIFA World Cup titles?',
    answers: ['Germany', 'Argentina', 'Brazil', 'Italy'],
    correctIndex: 2,
    explanation: 'Brazil has won the FIFA World Cup a record 5 times.',
  },
  {
    id: 'daily-tech-1',
    category: 'daily',
    subject: 'Technology',
    difficulty: 'Easy',
    prompt: 'What does "CPU" stand for?',
    answers: [
      'Central Processing Unit',
      'Computer Personal Unit',
      'Central Program Utility',
      'Core Processing Unit',
    ],
    correctIndex: 0,
    explanation: 'CPU stands for Central Processing Unit, the brain of the computer.',
  },
  {
    id: 'daily-tech-2',
    category: 'daily',
    subject: 'Technology',
    difficulty: 'Medium',
    prompt: 'Who founded Microsoft?',
    answers: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Jeff Bezos'],
    correctIndex: 1,
    explanation: 'Bill Gates co-founded Microsoft with Paul Allen in 1975.',
  },
  {
    id: 'daily-astro-1',
    category: 'daily',
    subject: 'Astronomy',
    difficulty: 'Easy',
    prompt: 'What is the closest planet to the Sun?',
    answers: ['Venus', 'Mercury', 'Earth', 'Mars'],
    correctIndex: 1,
    explanation: 'Mercury is the closest planet to the Sun.',
  },
  {
    id: 'daily-astro-2',
    category: 'daily',
    subject: 'Astronomy',
    difficulty: 'Medium',
    prompt: 'How many planets are in our solar system?',
    answers: ['7', '8', '9', '10'],
    correctIndex: 1,
    explanation: 'There are 8 recognized planets in our solar system (Pluto was reclassified as a dwarf planet).',
  },
  // ─── DEPARTMENT: Computer Science ─────────────────────────
  {
    id: 'dept-cs-1',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Medium',
    prompt: 'Which data structure follows FIFO order?',
    answers: ['Stack', 'Queue', 'Tree', 'Graph'],
    correctIndex: 1,
    explanation: 'Queues are first-in, first-out structures.',
  },
  {
    id: 'dept-cs-2',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Easy',
    prompt: 'What does HTML stand for?',
    answers: [
      'HyperText Markup Language',
      'High Tech Modern Language',
      'HyperTransfer Markup Language',
      'Home Tool Markup Language',
    ],
    correctIndex: 0,
    explanation: 'HTML stands for HyperText Markup Language.',
  },
  {
    id: 'dept-cs-3',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Hard',
    prompt: 'Which of these is not a programming language?',
    answers: ['Python', 'Java', 'HTML', 'C++'],
    correctIndex: 2,
    explanation: 'HTML is a markup language, not a programming language.',
  },
  {
    id: 'dept-cs-4',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Medium',
    prompt: 'What is the time complexity of binary search?',
    answers: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'],
    correctIndex: 1,
    explanation: 'Binary search has O(log n) time complexity.',
  },
  {
    id: 'dept-cs-5',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Easy',
    prompt: 'What is the full meaning of "RAM"?',
    answers: [
      'Read Access Memory',
      'Random Access Memory',
      'Read And Memory',
      'Rapid Access Module',
    ],
    correctIndex: 1,
    explanation: 'RAM stands for Random Access Memory.',
  },
  {
    id: 'dept-cs-6',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Hard',
    prompt: 'Which of these is a functional programming language?',
    answers: ['Java', 'C++', 'Haskell', 'Python'],
    correctIndex: 2,
    explanation: 'Haskell is a purely functional programming language.',
  },
  {
    id: 'dept-cs-7',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Medium',
    prompt: 'What does "SQL" stand for?',
    answers: [
      'Structured Query Language',
      'Simple Query Language',
      'Standard Query Language',
      'Sequential Query Language',
    ],
    correctIndex: 0,
    explanation: 'SQL stands for Structured Query Language, used for database management.',
  },
  {
    id: 'dept-cs-8',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Easy',
    prompt: 'Which device is used to input data into a computer?',
    answers: ['Monitor', 'Keyboard', 'Printer', 'Speaker'],
    correctIndex: 1,
    explanation: 'A keyboard is an input device used to enter data into a computer.',
  },
  // ─── DEPARTMENT: Medicine ─────────────────────────────────
  {
    id: 'dept-med-1',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Hard',
    prompt: 'How many bones are in the adult human body?',
    answers: ['106', '206', '306', '150'],
    correctIndex: 1,
    explanation: 'An adult human has 206 bones.',
  },
  {
    id: 'dept-med-2',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Medium',
    prompt: 'Which organ filters blood in the human body?',
    answers: ['Liver', 'Kidney', 'Heart', 'Lungs'],
    correctIndex: 1,
    explanation: 'The kidneys filter waste products from the blood to produce urine.',
  },
  {
    id: 'dept-med-3',
    category: 'department',
    subject: 'Physiology',
    difficulty: 'Easy',
    prompt: 'What is the normal human body temperature in Celsius?',
    answers: ['35°C', '36°C', '37°C', '38°C'],
    correctIndex: 2,
    explanation: 'Normal human body temperature is approximately 37°C (98.6°F).',
  },
  {
    id: 'dept-med-4',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Hard',
    prompt: 'How many chambers does the human heart have?',
    answers: ['2', '3', '4', '5'],
    correctIndex: 2,
    explanation: 'The human heart has four chambers: two atria and two ventricles.',
  },
  {
    id: 'dept-med-5',
    category: 'department',
    subject: 'Pharmacology',
    difficulty: 'Medium',
    prompt: 'Which drug is commonly used as a pain reliever?',
    answers: ['Paracetamol', 'Metformin', 'Omeprazole', 'Atorvastatin'],
    correctIndex: 0,
    explanation: 'Paracetamol (acetaminophen) is a common analgesic and antipyretic.',
  },
  {
    id: 'dept-med-6',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Easy',
    prompt: 'What is the largest bone in the human body?',
    answers: ['Tibia', 'Femur', 'Humerus', 'Pelvis'],
    correctIndex: 1,
    explanation: 'The femur (thigh bone) is the longest and largest bone in the human body.',
  },
  // ─── DEPARTMENT: Engineering ──────────────────────────────
  {
    id: 'dept-eng-1',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Medium',
    prompt: 'What is the unit of electrical power?',
    answers: ['Volt', 'Ampere', 'Watt', 'Ohm'],
    correctIndex: 2,
    explanation: 'Electrical power is measured in watts (W).',
  },
  {
    id: 'dept-eng-2',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Easy',
    prompt: 'Which material is a good conductor of electricity?',
    answers: ['Rubber', 'Plastic', 'Copper', 'Wood'],
    correctIndex: 2,
    explanation: 'Copper is an excellent conductor of electricity, commonly used in wiring.',
  },
  {
    id: 'dept-eng-3',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Hard',
    prompt: 'What is the formula for Ohm\'s Law?',
    answers: ['V = IR', 'P = IV', 'R = V/I', 'All of the above'],
    correctIndex: 3,
    explanation: 'Ohm\'s Law relates voltage, current, and resistance: V = IR, and its variations.',
  },
  {
    id: 'dept-eng-4',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Medium',
    prompt: 'Which type of bridge uses cables suspended from towers?',
    answers: ['Arch bridge', 'Beam bridge', 'Suspension bridge', 'Truss bridge'],
    correctIndex: 2,
    explanation: 'A suspension bridge uses cables suspended between towers to support the deck.',
  },
  {
    id: 'dept-eng-5',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Easy',
    prompt: 'What does AC stand for in electricity?',
    answers: ['Alternating Current', 'Active Current', 'Absolute Current', 'Applied Current'],
    correctIndex: 0,
    explanation: 'AC stands for Alternating Current, where the flow of electric charge periodically reverses.',
  },
  // ─── DEPARTMENT: Law ──────────────────────────────────────
  {
    id: 'dept-law-1',
    category: 'department',
    subject: 'Law',
    difficulty: 'Easy',
    prompt: 'What is the supreme law of Nigeria?',
    answers: ['Criminal Code', 'Constitution', 'Penal Code', 'Common Law'],
    correctIndex: 1,
    explanation: 'The Constitution is the supreme law of Nigeria.',
  },
  {
    id: 'dept-law-2',
    category: 'department',
    subject: 'Law',
    difficulty: 'Medium',
    prompt: 'What does "habeas corpus" mean?',
    answers: [
      'Guilty until proven innocent',
      'You shall have the body',
      'Let the buyer beware',
      'The state decides',
    ],
    correctIndex: 1,
    explanation: 'Habeas corpus is a legal principle protecting against unlawful detention.',
  },
  {
    id: 'dept-law-3',
    category: 'department',
    subject: 'Law',
    difficulty: 'Hard',
    prompt: 'Which court is the highest in Nigeria?',
    answers: ['Court of Appeal', 'Supreme Court', 'Federal High Court', 'Sharia Court'],
    correctIndex: 1,
    explanation: 'The Supreme Court of Nigeria is the highest court in the land.',
  },
  {
    id: 'dept-law-4',
    category: 'department',
    subject: 'Law',
    difficulty: 'Medium',
    prompt: 'What is "mens rea"?',
    answers: [
      'The guilty act',
      'The guilty mind',
      'The innocent party',
      'The legal defense',
    ],
    correctIndex: 1,
    explanation: 'Mens rea refers to the intention or knowledge of wrongdoing in committing a crime.',
  },
  // ─── DEPARTMENT: Business / Commerce ──────────────────────
  {
    id: 'dept-com-1',
    category: 'department',
    subject: 'Commerce',
    difficulty: 'Medium',
    prompt: 'Which of these is a medium of exchange?',
    answers: ['Barter', 'Money', 'Labour', 'Land'],
    correctIndex: 1,
    explanation: 'Money serves as a medium of exchange in modern economies.',
  },
  {
    id: 'dept-com-2',
    category: 'department',
    subject: 'Business',
    difficulty: 'Easy',
    prompt: 'What is profit?',
    answers: [
      'Total revenue minus total cost',
      'Total sales plus expenses',
      'Total assets minus liabilities',
      'Total income before tax',
    ],
    correctIndex: 0,
    explanation: 'Profit = Total Revenue - Total Cost.',
  },
  {
    id: 'dept-com-3',
    category: 'department',
    subject: 'Business',
    difficulty: 'Medium',
    prompt: 'What does SWOT stand for in business analysis?',
    answers: [
      'Strengths, Weaknesses, Opportunities, Threats',
      'Sales, Workforce, Operations, Technology',
      'Strategy, Workflow, Objectives, Targets',
      'System, Web, Online, Technology',
    ],
    correctIndex: 0,
    explanation: 'SWOT analysis evaluates Strengths, Weaknesses, Opportunities, and Threats.',
  },
  {
    id: 'dept-com-4',
    category: 'department',
    subject: 'Commerce',
    difficulty: 'Hard',
    prompt: 'What is the law of diminishing returns?',
    answers: [
      'Adding more input eventually yields smaller output increases',
      'Returns always increase with more input',
      'Costs always decrease with production',
      'Revenue is always proportional to effort',
    ],
    correctIndex: 0,
    explanation: 'The law of diminishing marginal returns states that adding more of one factor of production eventually yields smaller per-unit increases.',
  },
  // ─── LEVEL: Mathematics ───────────────────────────────────
  {
    id: 'level-maths-1',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the derivative of x²?',
    answers: ['x', '2x', 'x²', '2'],
    correctIndex: 1,
    explanation: 'The derivative of x² with respect to x is 2x.',
  },
  {
    id: 'level-maths-2',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 7 × 8?',
    answers: ['48', '54', '56', '64'],
    correctIndex: 2,
    explanation: '7 × 8 = 56.',
  },
  {
    id: 'level-maths-3',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Hard',
    prompt: 'What is the integral of 2x dx?',
    answers: ['x² + C', '2x² + C', 'x + C', 'x²/2 + C'],
    correctIndex: 0,
    explanation: '∫2x dx = x² + C, where C is the constant of integration.',
  },
  {
    id: 'level-maths-4',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'If a = 3 and b = 4, what is the value of a² + b²?',
    answers: ['7', '12', '25', '49'],
    correctIndex: 2,
    explanation: '3² + 4² = 9 + 16 = 25.',
  },
  {
    id: 'level-maths-5',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is the next prime number after 7?',
    answers: ['8', '9', '10', '11'],
    correctIndex: 3,
    explanation: '11 is the next prime number after 7 (8, 9, and 10 are not prime).',
  },
  {
    id: 'level-maths-6',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Hard',
    prompt: 'What is the value of sin(90°)?',
    answers: ['0', '0.5', '1', 'Undefined'],
    correctIndex: 2,
    explanation: 'sin(90°) = 1.',
  },
  // ─── LEVEL: English ───────────────────────────────────────
  {
    id: 'level-eng-1',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Easy',
    prompt: 'Identify the correct sentence:',
    answers: [
      'She don\'t like coffee.',
      'She doesn\'t like coffee.',
      'She not like coffee.',
      'She no like coffee.',
    ],
    correctIndex: 1,
    explanation: '"She doesn\'t like coffee" is grammatically correct.',
  },
  {
    id: 'level-eng-2',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Medium',
    prompt: 'Which word is an adverb?',
    answers: ['Quick', 'Quickly', 'Quickness', 'Quicken'],
    correctIndex: 1,
    explanation: '"Quickly" is an adverb modifying a verb, adjective, or other adverb.',
  },
  {
    id: 'level-eng-3',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Hard',
    prompt: 'What is a palindrome?',
    answers: [
      'A word that reads the same forwards and backwards',
      'A word with multiple meanings',
      'A word that sounds like another word',
      'A word with silent letters',
    ],
    correctIndex: 0,
    explanation: 'A palindrome reads the same forwards and backwards, e.g., "radar" or "level".',
  },
  {
    id: 'level-eng-4',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Medium',
    prompt: 'Choose the correct spelling:',
    answers: ['Receive', 'Recieve', 'Receeve', 'Reseive'],
    correctIndex: 0,
    explanation: '"Receive" follows the rule: i before e except after c.',
  },
  // ─── LEVEL: Science ───────────────────────────────────────
  {
    id: 'level-sci-1',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'What is the chemical symbol for oxygen?',
    answers: ['Ox', 'O', 'O₂', 'Om'],
    correctIndex: 1,
    explanation: 'The chemical symbol for oxygen is O.',
  },
  {
    id: 'level-sci-2',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the boiling point of water in Celsius?',
    answers: ['90°C', '100°C', '110°C', '120°C'],
    correctIndex: 1,
    explanation: 'Water boils at 100°C at standard atmospheric pressure.',
  },
  {
    id: 'level-sci-3',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Hard',
    prompt: 'What is the powerhouse of the cell?',
    answers: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'],
    correctIndex: 2,
    explanation: 'Mitochondria are known as the powerhouse of the cell, producing ATP.',
  },
  {
    id: 'level-sci-4',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'Which planet is known as the Red Planet?',
    answers: ['Venus', 'Jupiter', 'Mars', 'Saturn'],
    correctIndex: 2,
    explanation: 'Mars is called the Red Planet due to its reddish appearance from iron oxide.',
  },
  // ─── FACULTY: Engineering ─────────────────────────────────
  {
    id: 'faculty-eng-1',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Easy',
    prompt: 'The first law of thermodynamics is about:',
    answers: ['Entropy', 'Conservation of energy', 'Absolute zero', 'Heat transfer'],
    correctIndex: 1,
    explanation: 'The first law states that energy cannot be created or destroyed, only converted.',
  },
  {
    id: 'faculty-eng-2',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Medium',
    prompt: 'What is the second law of thermodynamics?',
    answers: [
      'Energy is conserved',
      'Entropy always increases',
      'Absolute zero is unattainable',
      'Heat flows from cold to hot',
    ],
    correctIndex: 1,
    explanation: 'The second law states that the total entropy of an isolated system always increases over time.',
  },
  {
    id: 'faculty-eng-3',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Hard',
    prompt: 'What is Young\'s modulus a measure of?',
    answers: ['Hardness', 'Stiffness', 'Toughness', 'Ductility'],
    correctIndex: 1,
    explanation: 'Young\'s modulus measures the stiffness of a material.',
  },
  {
    id: 'faculty-eng-4',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Medium',
    prompt: 'Which of these is a renewable energy source?',
    answers: ['Coal', 'Natural gas', 'Solar', 'Nuclear'],
    correctIndex: 2,
    explanation: 'Solar energy is renewable, while coal, gas, and nuclear are non-renewable.',
  },
  // ─── FACULTY: Science ─────────────────────────────────────
  {
    id: 'faculty-sci-1',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'What is the most abundant gas in Earth\'s atmosphere?',
    answers: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'],
    correctIndex: 2,
    explanation: 'Nitrogen makes up about 78% of Earth\'s atmosphere.',
  },
  {
    id: 'faculty-sci-2',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the pH of a strong acid?',
    answers: ['Close to 0', 'Close to 7', 'Close to 14', 'Exactly 7'],
    correctIndex: 0,
    explanation: 'Strong acids have pH values close to 0.',
  },
  {
    id: 'faculty-sci-3',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Hard',
    prompt: 'What is the half-life of Carbon-14?',
    answers: ['1,000 years', '3,730 years', '5,730 years', '10,000 years'],
    correctIndex: 2,
    explanation: 'Carbon-14 has a half-life of approximately 5,730 years.',
  },
  {
    id: 'faculty-sci-4',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'Which gas do plants absorb from the atmosphere?',
    answers: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctIndex: 2,
    explanation: 'Plants absorb carbon dioxide for photosynthesis.',
  },
  // ─── FACULTY: Arts ────────────────────────────────────────
  {
    id: 'faculty-arts-1',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Easy',
    prompt: 'Who painted the Mona Lisa?',
    answers: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Van Gogh'],
    correctIndex: 1,
    explanation: 'Leonardo da Vinci painted the Mona Lisa in the early 16th century.',
  },
  {
    id: 'faculty-arts-2',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Medium',
    prompt: 'What are the primary colors?',
    answers: [
      'Red, Green, Blue',
      'Red, Yellow, Blue',
      'Red, White, Blue',
      'Green, Yellow, Purple',
    ],
    correctIndex: 1,
    explanation: 'The primary colors are red, yellow, and blue.',
  },
  {
    id: 'faculty-arts-3',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Hard',
    prompt: 'Which art movement is Salvador Dalí associated with?',
    answers: ['Impressionism', 'Cubism', 'Surrealism', 'Realism'],
    correctIndex: 2,
    explanation: 'Salvador Dalí was a prominent surrealist artist.',
  },
  {
    id: 'faculty-arts-4',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Medium',
    prompt: 'What is the art of paper folding called?',
    answers: ['Origami', 'Calligraphy', 'Sculpture', 'Collage'],
    correctIndex: 0,
    explanation: 'Origami is the Japanese art of paper folding.',
  },
  // ─── APTITUDE: Logical Reasoning ──────────────────────────
  {
    id: 'aptitude-1',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Hard',
    prompt: 'All roses are flowers. Some flowers fade quickly. Which statement must be true?',
    answers: [
      'All roses fade quickly',
      'Some roses fade quickly',
      'Some flowers are roses',
      'No roses fade quickly',
    ],
    correctIndex: 2,
    explanation: 'If all roses are flowers, then at least some flowers are roses when roses exist.',
  },
  {
    id: 'aptitude-2',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Medium',
    prompt: 'If all A are B, and all B are C, then:',
    answers: [
      'All A are C',
      'All C are A',
      'Some A are not C',
      'No relationship exists',
    ],
    correctIndex: 0,
    explanation: 'If all A are B and all B are C, then all A are C by transitive property.',
  },
  {
    id: 'aptitude-3',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Easy',
    prompt: 'Which number comes next: 2, 4, 6, 8, ?',
    answers: ['9', '10', '11', '12'],
    correctIndex: 1,
    explanation: 'The sequence increases by 2 each time: 2, 4, 6, 8, 10.',
  },
  {
    id: 'aptitude-4',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Hard',
    prompt: 'If you rearrange the letters "CIFAIPC", you get the name of a(n):',
    answers: ['City', 'Animal', 'Ocean', 'Country'],
    correctIndex: 2,
    explanation: '"CIFAIPC" rearranges to "PACIFIC" - an ocean.',
  },
  {
    id: 'aptitude-5',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Medium',
    prompt: 'A clock shows 3:15. What is the angle between the hour and minute hands?',
    answers: ['0°', '7.5°', '15°', '30°'],
    correctIndex: 1,
    explanation: 'At 3:15, the hour hand has moved ¼ of the way between 3 and 4, which is 7.5° ahead of the minute hand.',
  },
  {
    id: 'aptitude-6',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Easy',
    prompt: 'Which word does not belong? Apple, Banana, Carrot, Mango',
    answers: ['Apple', 'Banana', 'Carrot', 'Mango'],
    correctIndex: 2,
    explanation: 'Carrot is a vegetable, while the others are fruits.',
  },
  {
    id: 'aptitude-7',
    category: 'aptitude',
    subject: 'Numerical Reasoning',
    difficulty: 'Medium',
    prompt: 'What is 20% of 50% of 200?',
    answers: ['10', '20', '30', '40'],
    correctIndex: 1,
    explanation: '50% of 200 = 100. 20% of 100 = 20.',
  },
  {
    id: 'aptitude-8',
    category: 'aptitude',
    subject: 'Verbal Reasoning',
    difficulty: 'Hard',
    prompt: 'Find the odd one out:',
    answers: ['Triangle', 'Square', 'Circle', 'Rectangle'],
    correctIndex: 2,
    explanation: 'A circle has no straight edges, while the others are polygons.',
  },
  {
    id: 'aptitude-9',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Medium',
    prompt: 'If today is Monday, what day will it be in 100 days?',
    answers: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    correctIndex: 1,
    explanation: '100 mod 7 = 2. Monday + 2 days = Wednesday.',
  },
  {
    id: 'aptitude-10',
    category: 'aptitude',
    subject: 'Numerical Reasoning',
    difficulty: 'Easy',
    prompt: 'What is the average of 10, 20, and 30?',
    answers: ['15', '20', '25', '30'],
    correctIndex: 1,
    explanation: 'Average = (10 + 20 + 30) / 3 = 60 / 3 = 20.',
  },
  // ─── GENERAL KNOWLEDGE ────────────────────────────────────
  {
    id: 'gk-1',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Easy',
    prompt: 'Which continent is Nigeria located in?',
    answers: ['Asia', 'Africa', 'Europe', 'South America'],
    correctIndex: 1,
    explanation: 'Nigeria is in West Africa.',
  },
  {
    id: 'gk-2',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Medium',
    prompt: 'Who is the current Secretary-General of the United Nations?',
    answers: ['Ban Ki-moon', 'António Guterres', 'Kofi Annan', 'Boutros Boutros-Ghali'],
    correctIndex: 1,
    explanation: 'António Guterres has been the UN Secretary-General since 2017.',
  },
  {
    id: 'gk-3',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Easy',
    prompt: 'How many countries are in Africa?',
    answers: ['44', '54', '64', '74'],
    correctIndex: 1,
    explanation: 'There are 54 recognized countries in Africa.',
  },
  {
    id: 'gk-4',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Hard',
    prompt: 'What is the currency of Japan?',
    answers: ['Yuan', 'Won', 'Yen', 'Ringgit'],
    correctIndex: 2,
    explanation: 'The Japanese currency is the yen (¥).',
  },
  {
    id: 'gk-5',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Medium',
    prompt: 'Which organization won the Nobel Peace Prize in 2023?',
    answers: ['WHO', 'UNICEF', 'Narges Mohammadi', 'ICRC'],
    correctIndex: 2,
    explanation: 'Narges Mohammadi won the 2023 Nobel Peace Prize for her fight against oppression in Iran.',
  },
  {
    id: 'gk-6',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Easy',
    prompt: 'What is the largest country in the world by area?',
    answers: ['China', 'USA', 'Russia', 'Canada'],
    correctIndex: 2,
    explanation: 'Russia is the largest country by area, covering about 17.1 million km².',
  },
  {
    id: 'gk-7',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Medium',
    prompt: 'Which year did World War II end?',
    answers: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
    explanation: 'World War II ended in 1945.',
  },
  {
    id: 'gk-8',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Hard',
    prompt: 'What is the official language of Brazil?',
    answers: ['Spanish', 'Portuguese', 'French', 'English'],
    correctIndex: 1,
    explanation: 'Portuguese is the official language of Brazil.',
  },
  {
    id: 'gk-9',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Easy',
    prompt: 'Which animal is known as the "King of the Jungle"?',
    answers: ['Tiger', 'Lion', 'Elephant', 'Gorilla'],
    correctIndex: 1,
    explanation: 'The lion is traditionally known as the "King of the Jungle".',
  },
  {
    id: 'gk-10',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Medium',
    prompt: 'What is the tallest mountain in the world?',
    answers: ['K2', 'Mount Everest', 'Kilimanjaro', 'Denali'],
    correctIndex: 1,
    explanation: 'Mount Everest is the tallest mountain at 8,848 meters above sea level.',
  },
  {
    id: 'gk-11',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Hard',
    prompt: 'Which country is known as the "Land of the Rising Sun"?',
    answers: ['China', 'South Korea', 'Japan', 'Thailand'],
    correctIndex: 2,
    explanation: 'Japan is called the "Land of the Rising Sun".',
  },
  {
    id: 'gk-12',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Easy',
    prompt: 'How many days are in a leap year?',
    answers: ['364', '365', '366', '367'],
    correctIndex: 2,
    explanation: 'A leap year has 366 days, with an extra day in February (29th).',
  },
  {
    id: 'gk-13',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Medium',
    prompt: 'What is the largest organ in the human body?',
    answers: ['Liver', 'Brain', 'Skin', 'Heart'],
    correctIndex: 2,
    explanation: 'The skin is the largest organ, covering about 1.5-2 square meters.',
  },
  {
    id: 'gk-14',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Easy',
    prompt: 'Which gas do humans breathe out?',
    answers: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctIndex: 2,
    explanation: 'Humans exhale carbon dioxide as a waste product of respiration.',
  },
  {
    id: 'gk-15',
    category: 'general-knowledge',
    subject: 'Current Affairs',
    difficulty: 'Hard',
    prompt: 'What is the longest river in Africa?',
    answers: ['Congo', 'Niger', 'Nile', 'Zambezi'],
    correctIndex: 2,
    explanation: 'The Nile River is the longest river in Africa and the world.',
  },
  // ─── SPEED QUIZ: Quick Questions ──────────────────────────
  {
    id: 'speed-maths-1',
    category: 'speed-quiz',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'If 3x + 7 = 28, what is the value of x?',
    answers: ['5', '6', '7', '9'],
    correctIndex: 2,
    explanation: 'Subtract 7 from both sides to get 3x = 21, then divide by 3.',
  },
  {
    id: 'speed-maths-2',
    category: 'speed-quiz',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 12 × 12?',
    answers: ['124', '134', '144', '154'],
    correctIndex: 2,
    explanation: '12 × 12 = 144.',
  },
  {
    id: 'speed-maths-3',
    category: 'speed-quiz',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 100 ÷ 4?',
    answers: ['15', '20', '25', '30'],
    correctIndex: 2,
    explanation: '100 ÷ 4 = 25.',
  },
  {
    id: 'speed-maths-4',
    category: 'speed-quiz',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is 15 × 15?',
    answers: ['200', '215', '225', '250'],
    correctIndex: 2,
    explanation: '15 × 15 = 225.',
  },
  {
    id: 'speed-sci-1',
    category: 'speed-quiz',
    subject: 'Science',
    difficulty: 'Easy',
    prompt: 'What is H₂O commonly known as?',
    answers: ['Salt', 'Sugar', 'Water', 'Acid'],
    correctIndex: 2,
    explanation: 'H₂O is the chemical formula for water.',
  },
  {
    id: 'speed-sci-2',
    category: 'speed-quiz',
    subject: 'Science',
    difficulty: 'Easy',
    prompt: 'What is the freezing point of water in Celsius?',
    answers: ['-1°C', '0°C', '1°C', '2°C'],
    correctIndex: 1,
    explanation: 'Water freezes at 0°C.',
  },
  {
    id: 'speed-sci-3',
    category: 'speed-quiz',
    subject: 'Science',
    difficulty: 'Medium',
    prompt: 'What planet is known as the "Morning Star"?',
    answers: ['Mars', 'Jupiter', 'Venus', 'Mercury'],
    correctIndex: 2,
    explanation: 'Venus is often called the "Morning Star" or "Evening Star".',
  },
  {
    id: 'speed-gk-1',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'What color do you get by mixing red and blue?',
    answers: ['Green', 'Purple', 'Orange', 'Yellow'],
    correctIndex: 1,
    explanation: 'Red and blue make purple.',
  },
  {
    id: 'speed-gk-2',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'How many sides does a triangle have?',
    answers: ['2', '3', '4', '5'],
    correctIndex: 1,
    explanation: 'A triangle has three sides.',
  },
  {
    id: 'speed-gk-3',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Medium',
    prompt: 'Which month has 28 days?',
    answers: ['February only', 'All months', 'February in leap years only', 'January'],
    correctIndex: 1,
    explanation: 'All months have at least 28 days.',
  },
  {
    id: 'speed-gk-4',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'What is the opposite of "hot"?',
    answers: ['Warm', 'Cool', 'Cold', 'Mild'],
    correctIndex: 2,
    explanation: 'The opposite of "hot" is "cold".',
  },
  {
    id: 'speed-gk-5',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'How many legs does a spider have?',
    answers: ['6', '8', '10', '12'],
    correctIndex: 1,
    explanation: 'Spiders have 8 legs.',
  },
  {
    id: 'speed-gk-6',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Medium',
    prompt: 'What is the smallest prime number?',
    answers: ['0', '1', '2', '3'],
    correctIndex: 2,
    explanation: '2 is the smallest prime number.',
  },
  {
    id: 'speed-gk-7',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'Which direction does the sun rise?',
    answers: ['North', 'South', 'East', 'West'],
    correctIndex: 2,
    explanation: 'The sun rises in the east.',
  },
  {
    id: 'speed-gk-8',
    category: 'speed-quiz',
    subject: 'General Knowledge',
    difficulty: 'Medium',
    prompt: 'How many zeros are in one million?',
    answers: ['4', '5', '6', '7'],
    correctIndex: 2,
    explanation: 'One million = 1,000,000 (6 zeros).',
  },
  // ─── DAILY: More Mixed Questions ──────────────────────────
  {
    id: 'daily-maths-3',
    category: 'daily',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the value of 6 × 7?',
    answers: ['40', '42', '48', '54'],
    correctIndex: 1,
    explanation: '6 × 7 = 42.',
  },
  {
    id: 'daily-maths-4',
    category: 'daily',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 100 - 37?',
    answers: ['53', '63', '73', '83'],
    correctIndex: 1,
    explanation: '100 - 37 = 63.',
  },
  {
    id: 'daily-eng-3',
    category: 'daily',
    subject: 'English',
    difficulty: 'Medium',
    prompt: 'What is the plural of "city"?',
    answers: ['Citys', 'Cities', 'Cityes', 'Citis'],
    correctIndex: 1,
    explanation: 'For words ending in consonant + y, change y to ies: city → cities.',
  },
  {
    id: 'daily-eng-4',
    category: 'daily',
    subject: 'English',
    difficulty: 'Easy',
    prompt: 'Which word is a pronoun?',
    answers: ['Run', 'They', 'Quickly', 'Beautiful'],
    correctIndex: 1,
    explanation: '"They" is a pronoun that replaces a noun.',
  },
  {
    id: 'daily-phys-3',
    category: 'daily',
    subject: 'Physics',
    difficulty: 'Medium',
    prompt: 'What is the unit of energy?',
    answers: ['Newton', 'Joule', 'Watt', 'Pascal'],
    correctIndex: 1,
    explanation: 'Energy is measured in joules (J).',
  },
  {
    id: 'daily-chem-3',
    category: 'daily',
    subject: 'Chemistry',
    difficulty: 'Easy',
    prompt: 'What is the chemical symbol for carbon?',
    answers: ['Ca', 'C', 'Co', 'Cr'],
    correctIndex: 1,
    explanation: 'Carbon\'s chemical symbol is C.',
  },
  {
    id: 'daily-bio-3',
    category: 'daily',
    subject: 'Biology',
    difficulty: 'Medium',
    prompt: 'What is the main function of the heart?',
    answers: ['Digest food', 'Pump blood', 'Filter waste', 'Store energy'],
    correctIndex: 1,
    explanation: 'The heart pumps blood throughout the body.',
  },
  {
    id: 'daily-his-3',
    category: 'daily',
    subject: 'History',
    difficulty: 'Medium',
    prompt: 'Who was the first President of the United States?',
    answers: ['Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams'],
    correctIndex: 1,
    explanation: 'George Washington was the first President of the United States.',
  },
  {
    id: 'daily-geo-3',
    category: 'daily',
    subject: 'Geography',
    difficulty: 'Easy',
    prompt: 'What is the capital of the United States?',
    answers: ['New York', 'Washington D.C.', 'Los Angeles', 'Chicago'],
    correctIndex: 1,
    explanation: 'Washington D.C. is the capital of the United States.',
  },
  {
    id: 'daily-sport-3',
    category: 'daily',
    subject: 'Sports',
    difficulty: 'Medium',
    prompt: 'How many players are on a cricket team?',
    answers: ['9', '10', '11', '12'],
    correctIndex: 2,
    explanation: 'A cricket team has 11 players.',
  },
  {
    id: 'daily-tech-3',
    category: 'daily',
    subject: 'Technology',
    difficulty: 'Medium',
    prompt: 'What does "AI" stand for?',
    answers: ['Artificial Intelligence', 'Automated Input', 'Advanced Internet', 'Applied Information'],
    correctIndex: 0,
    explanation: 'AI stands for Artificial Intelligence.',
  },
  {
    id: 'daily-astro-3',
    category: 'daily',
    subject: 'Astronomy',
    difficulty: 'Medium',
    prompt: 'What is the largest planet in our solar system?',
    answers: ['Earth', 'Jupiter', 'Saturn', 'Neptune'],
    correctIndex: 1,
    explanation: 'Jupiter is the largest planet in our solar system.',
  },
  {
    id: 'daily-gk-1',
    category: 'daily',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'What is the largest mammal in the world?',
    answers: ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'],
    correctIndex: 1,
    explanation: 'The blue whale is the largest mammal in the world.',
  },
  {
    id: 'daily-gk-2',
    category: 'daily',
    subject: 'General Knowledge',
    difficulty: 'Medium',
    prompt: 'How many continents are there in the world?',
    answers: ['5', '6', '7', '8'],
    correctIndex: 2,
    explanation: 'There are 7 continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.',
  },
  {
    id: 'daily-gk-3',
    category: 'daily',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'What is the fastest land animal?',
    answers: ['Lion', 'Cheetah', 'Leopard', 'Horse'],
    correctIndex: 1,
    explanation: 'The cheetah is the fastest land animal, reaching speeds up to 120 km/h.',
  },
  // ─── DEPARTMENT: More Computer Science ────────────────────
  {
    id: 'dept-cs-9',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Medium',
    prompt: 'What is the output of 2 + 2 in JavaScript?',
    answers: ['22', '4', '2+2', 'Error'],
    correctIndex: 1,
    explanation: 'In JavaScript, 2 + 2 = 4.',
  },
  {
    id: 'dept-cs-10',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Hard',
    prompt: 'What is the difference between a compiler and an interpreter?',
    answers: ['No difference', 'Compiler translates entire program, interpreter translates line by line', 'Interpreter is faster', 'Compiler is for web only'],
    correctIndex: 1,
    explanation: 'A compiler translates the entire program at once, while an interpreter translates and executes line by line.',
  },
  {
    id: 'dept-cs-11',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Easy',
    prompt: 'What does "CSS" stand for?',
    answers: ['Cascading Style Sheets', 'Computer Style System', 'Creative Style Sheets', 'Cascading System Sheets'],
    correctIndex: 0,
    explanation: 'CSS stands for Cascading Style Sheets.',
  },
  {
    id: 'dept-cs-12',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Medium',
    prompt: 'What is the time complexity of linear search?',
    answers: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    correctIndex: 2,
    explanation: 'Linear search has O(n) time complexity in the worst case.',
  },
  {
    id: 'dept-cs-13',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Hard',
    prompt: 'What is the difference between "==" and "===" in JavaScript?',
    answers: ['No difference', '"==" compares values, "===" compares values and types', '"===" compares only types', '"==" is faster'],
    correctIndex: 1,
    explanation: '"==" performs type coercion, while "===" compares both value and type without coercion.',
  },
  {
    id: 'dept-cs-14',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Easy',
    prompt: 'What is the full meaning of "URL"?',
    answers: ['Uniform Resource Locator', 'Universal Resource Link', 'Uniform Reference Locator', 'Universal Reference Link'],
    correctIndex: 0,
    explanation: 'URL stands for Uniform Resource Locator.',
  },
  // ─── DEPARTMENT: More Medicine ────────────────────────────
  {
    id: 'dept-med-7',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Medium',
    prompt: 'What is the smallest bone in the human body?',
    answers: ['Femur', 'Stapes', 'Tibia', 'Radius'],
    correctIndex: 1,
    explanation: 'The stapes (stirrup bone) in the ear is the smallest bone in the human body.',
  },
  {
    id: 'dept-med-8',
    category: 'department',
    subject: 'Physiology',
    difficulty: 'Easy',
    prompt: 'What is the normal resting heart rate for adults?',
    answers: ['40-60 bpm', '60-100 bpm', '100-140 bpm', '140-180 bpm'],
    correctIndex: 1,
    explanation: 'The normal resting heart rate for adults is 60-100 beats per minute.',
  },
  {
    id: 'dept-med-9',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Hard',
    prompt: 'How many pairs of ribs does the human body have?',
    answers: ['10', '12', '14', '16'],
    correctIndex: 1,
    explanation: 'The human body has 12 pairs of ribs.',
  },
  {
    id: 'dept-med-10',
    category: 'department',
    subject: 'Pharmacology',
    difficulty: 'Medium',
    prompt: 'What is the main function of antibiotics?',
    answers: ['Kill viruses', 'Kill bacteria', 'Reduce pain', 'Lower blood pressure'],
    correctIndex: 1,
    explanation: 'Antibiotics are used to treat bacterial infections.',
  },
  {
    id: 'dept-med-11',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Easy',
    prompt: 'What is the main function of the lungs?',
    answers: ['Pump blood', 'Exchange oxygen and carbon dioxide', 'Digest food', 'Filter waste'],
    correctIndex: 1,
    explanation: 'The lungs are responsible for gas exchange - taking in oxygen and releasing carbon dioxide.',
  },
  {
    id: 'dept-med-12',
    category: 'department',
    subject: 'Physiology',
    difficulty: 'Hard',
    prompt: 'What is the normal blood pressure reading for adults?',
    answers: ['80/60 mmHg', '120/80 mmHg', '160/100 mmHg', '200/120 mmHg'],
    correctIndex: 1,
    explanation: 'Normal blood pressure for adults is approximately 120/80 mmHg.',
  },
  // ─── DEPARTMENT: More Engineering ─────────────────────────
  {
    id: 'dept-eng-6',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Medium',
    prompt: 'What is the unit of electrical resistance?',
    answers: ['Volt', 'Ampere', 'Ohm', 'Watt'],
    correctIndex: 2,
    explanation: 'Electrical resistance is measured in ohms (Ω).',
  },
  {
    id: 'dept-eng-7',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Easy',
    prompt: 'What is the main material used in construction?',
    answers: ['Plastic', 'Concrete', 'Rubber', 'Glass'],
    correctIndex: 1,
    explanation: 'Concrete is the most widely used construction material.',
  },
  {
    id: 'dept-eng-8',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Hard',
    prompt: 'What is the difference between stress and strain?',
    answers: ['No difference', 'Stress is force per area, strain is deformation', 'Strain is force per area, stress is deformation', 'Both are the same'],
    correctIndex: 1,
    explanation: 'Stress is the force applied per unit area, while strain is the resulting deformation.',
  },
  {
    id: 'dept-eng-9',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Medium',
    prompt: 'What is the function of a transformer?',
    answers: ['Generate electricity', 'Change voltage levels', 'Store energy', 'Measure current'],
    correctIndex: 1,
    explanation: 'A transformer changes the voltage level of alternating current.',
  },
  {
    id: 'dept-eng-10',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Easy',
    prompt: 'What does "DC" stand for in electricity?',
    answers: ['Direct Current', 'Dynamic Current', 'Digital Current', 'Dual Current'],
    correctIndex: 0,
    explanation: 'DC stands for Direct Current, where electric charge flows in one direction.',
  },
  {
    id: 'dept-eng-11',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Hard',
    prompt: 'What is the second law of thermodynamics?',
    answers: ['Energy is conserved', 'Entropy always increases', 'Absolute zero is unattainable', 'Heat flows from cold to hot'],
    correctIndex: 1,
    explanation: 'The second law states that the total entropy of an isolated system always increases over time.',
  },
  // ─── DEPARTMENT: More Law ─────────────────────────────────
  {
    id: 'dept-law-5',
    category: 'department',
    subject: 'Law',
    difficulty: 'Medium',
    prompt: 'What is the difference between civil and criminal law?',
    answers: ['No difference', 'Civil law deals with disputes between individuals, criminal law deals with offenses against the state', 'Criminal law is always more serious', 'Civil law is for businesses only'],
    correctIndex: 1,
    explanation: 'Civil law resolves disputes between individuals, while criminal law deals with offenses against the state.',
  },
  {
    id: 'dept-law-6',
    category: 'department',
    subject: 'Law',
    difficulty: 'Easy',
    prompt: 'What is a contract?',
    answers: ['A type of crime', 'A legally binding agreement', 'A court judgment', 'A government policy'],
    correctIndex: 1,
    explanation: 'A contract is a legally binding agreement between two or more parties.',
  },
  {
    id: 'dept-law-7',
    category: 'department',
    subject: 'Law',
    difficulty: 'Hard',
    prompt: 'What is the difference between a tort and a crime?',
    answers: ['No difference', 'A tort is a civil wrong, a crime is an offense against the state', 'A crime is always more serious', 'A tort is for businesses only'],
    correctIndex: 1,
    explanation: 'A tort is a civil wrong that causes harm, while a crime is an offense against the state.',
  },
  {
    id: 'dept-law-8',
    category: 'department',
    subject: 'Law',
    difficulty: 'Medium',
    prompt: 'What is the burden of proof in criminal cases?',
    answers: ['Balance of probabilities', 'Beyond reasonable doubt', 'Preponderance of evidence', 'Clear and convincing evidence'],
    correctIndex: 1,
    explanation: 'In criminal cases, the prosecution must prove guilt beyond a reasonable doubt.',
  },
  // ─── DEPARTMENT: More Business / Commerce ────────────────
  {
    id: 'dept-com-5',
    category: 'department',
    subject: 'Business',
    difficulty: 'Medium',
    prompt: 'What is the difference between a sole proprietorship and a partnership?',
    answers: ['No difference', 'Sole proprietorship has one owner, partnership has two or more', 'Partnership is always larger', 'Sole proprietorship is illegal'],
    correctIndex: 1,
    explanation: 'A sole proprietorship is owned by one person, while a partnership is owned by two or more people.',
  },
  {
    id: 'dept-com-6',
    category: 'department',
    subject: 'Commerce',
    difficulty: 'Easy',
    prompt: 'What is the main purpose of a business?',
    answers: ['To lose money', 'To make a profit', 'To pay taxes', 'To hire workers'],
    correctIndex: 1,
    explanation: 'The main purpose of a business is to make a profit by providing goods or services.',
  },
  {
    id: 'dept-com-7',
    category: 'department',
    subject: 'Business',
    difficulty: 'Hard',
    prompt: 'What is the difference between a merger and an acquisition?',
    answers: ['No difference', 'Merger combines two companies, acquisition is one company buying another', 'Acquisition is always larger', 'Merger is illegal'],
    correctIndex: 1,
    explanation: 'A merger combines two companies into one, while an acquisition is one company purchasing another.',
  },
  {
    id: 'dept-com-8',
    category: 'department',
    subject: 'Commerce',
    difficulty: 'Medium',
    prompt: 'What is the function of a marketing department?',
    answers: ['Manufacture products', 'Promote and sell products', 'Manage finances', 'Hire employees'],
    correctIndex: 1,
    explanation: 'The marketing department promotes and sells products to customers.',
  },
  // ─── LEVEL: More Mathematics ──────────────────────────────
  {
    id: 'level-maths-7',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the value of 4³?',
    answers: ['16', '32', '64', '128'],
    correctIndex: 2,
    explanation: '4³ = 4 × 4 × 4 = 64.',
  },
  {
    id: 'level-maths-8',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 15 + 27?',
    answers: ['40', '42', '44', '46'],
    correctIndex: 1,
    explanation: '15 + 27 = 42.',
  },
  {
    id: 'level-maths-9',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Hard',
    prompt: 'What is the value of the limit as x→0 of (1 - cos x)/x²?',
    answers: ['0', '0.5', '1', '2'],
    correctIndex: 1,
    explanation: 'The limit of (1 - cos x)/x² as x approaches 0 is 1/2.',
  },
  {
    id: 'level-maths-10',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the value of 2⁵?',
    answers: ['16', '32', '64', '128'],
    correctIndex: 1,
    explanation: '2⁵ = 2 × 2 × 2 × 2 × 2 = 32.',
  },
  // ─── LEVEL: More English ──────────────────────────────────
  {
    id: 'level-eng-5',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Medium',
    prompt: 'What is the correct plural of "child"?',
    answers: ['Childs', 'Childes', 'Children', 'Child\'s'],
    correctIndex: 2,
    explanation: '"Children" is the irregular plural form of "child".',
  },
  {
    id: 'level-eng-6',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Easy',
    prompt: 'Which word is a conjunction?',
    answers: ['Run', 'And', 'Quickly', 'Beautiful'],
    correctIndex: 1,
    explanation: '"And" is a conjunction that connects words or phrases.',
  },
  {
    id: 'level-eng-7',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Hard',
    prompt: 'What is the meaning of the word "ambiguous"?',
    answers: ['Clear', 'Having multiple meanings', 'Simple', 'Powerful'],
    correctIndex: 1,
    explanation: '"Ambiguous" means having more than one possible meaning or interpretation.',
  },
  {
    id: 'level-eng-8',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Medium',
    prompt: 'Choose the correct spelling:',
    answers: ['Definitely', 'Definately', 'Definitly', 'Definately'],
    correctIndex: 0,
    explanation: '"Definitely" is the correct spelling.',
  },
  // ─── LEVEL: More Science ──────────────────────────────────
  {
    id: 'level-sci-5',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the chemical symbol for hydrogen?',
    answers: ['H', 'He', 'Hy', 'Hd'],
    correctIndex: 0,
    explanation: 'Hydrogen\'s chemical symbol is H.',
  },
  {
    id: 'level-sci-6',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'What is the freezing point of water in Fahrenheit?',
    answers: ['0°F', '32°F', '100°F', '212°F'],
    correctIndex: 1,
    explanation: 'Water freezes at 32°F.',
  },
  {
    id: 'level-sci-7',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Hard',
    prompt: 'What is the speed of light in a vacuum?',
    answers: ['3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '3 × 10⁴ m/s'],
    correctIndex: 1,
    explanation: 'The speed of light in a vacuum is approximately 3 × 10⁸ m/s.',
  },
  {
    id: 'level-sci-8',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the chemical formula for table salt?',
    answers: ['KCl', 'NaCl', 'CaCl₂', 'MgCl₂'],
    correctIndex: 1,
    explanation: 'Table salt is sodium chloride (NaCl).',
  },
  // ─── FACULTY: More Engineering ────────────────────────────
  {
    id: 'faculty-eng-5',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Medium',
    prompt: 'What is the unit of electrical power?',
    answers: ['Volt', 'Ampere', 'Watt', 'Ohm'],
    correctIndex: 2,
    explanation: 'Electrical power is measured in watts (W).',
  },
  {
    id: 'faculty-eng-6',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Easy',
    prompt: 'Which of these is a non-renewable energy source?',
    answers: ['Solar', 'Wind', 'Coal', 'Hydroelectric'],
    correctIndex: 2,
    explanation: 'Coal is a non-renewable fossil fuel.',
  },
  {
    id: 'faculty-eng-7',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Hard',
    prompt: 'What is the formula for calculating power?',
    answers: ['P = VI', 'P = V/I', 'P = I/V', 'P = V + I'],
    correctIndex: 0,
    explanation: 'Power = Voltage × Current (P = VI).',
  },
  {
    id: 'faculty-eng-8',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Medium',
    prompt: 'What is the main function of a generator?',
    answers: ['Store energy', 'Convert mechanical energy to electrical energy', 'Measure current', 'Change voltage'],
    correctIndex: 1,
    explanation: 'A generator converts mechanical energy into electrical energy.',
  },
  // ─── FACULTY: More Science ────────────────────────────────
  {
    id: 'faculty-sci-5',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the most abundant element in the universe?',
    answers: ['Oxygen', 'Hydrogen', 'Carbon', 'Helium'],
    correctIndex: 1,
    explanation: 'Hydrogen is the most abundant element in the universe.',
  },
  {
    id: 'faculty-sci-6',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'What is the chemical symbol for nitrogen?',
    answers: ['N', 'Ni', 'Na', 'Ne'],
    correctIndex: 0,
    explanation: 'Nitrogen\'s chemical symbol is N.',
  },
  {
    id: 'faculty-sci-7',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Hard',
    prompt: 'What is the theory of evolution by natural selection attributed to?',
    answers: ['Isaac Newton', 'Charles Darwin', 'Albert Einstein', 'Gregor Mendel'],
    correctIndex: 1,
    explanation: 'Charles Darwin proposed the theory of evolution by natural selection.',
  },
  {
    id: 'faculty-sci-8',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the main component of the Earth\'s core?',
    answers: ['Oxygen', 'Iron', 'Silicon', 'Carbon'],
    correctIndex: 1,
    explanation: 'The Earth\'s core is primarily composed of iron and nickel.',
  },
  // ─── FACULTY: More Arts ───────────────────────────────────
  {
    id: 'faculty-arts-5',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Medium',
    prompt: 'Who painted "The Starry Night"?',
    answers: ['Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dalí'],
    correctIndex: 1,
    explanation: 'Vincent van Gogh painted "The Starry Night".',
  },
  {
    id: 'faculty-arts-6',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Easy',
    prompt: 'What is the art of beautiful handwriting called?',
    answers: ['Origami', 'Calligraphy', 'Sculpture', 'Collage'],
    correctIndex: 1,
    explanation: 'Calligraphy is the art of beautiful handwriting.',
  },
  {
    id: 'faculty-arts-7',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Hard',
    prompt: 'Which art movement is Pablo Picasso associated with?',
    answers: ['Impressionism', 'Cubism', 'Surrealism', 'Realism'],
    correctIndex: 1,
    explanation: 'Pablo Picasso co-founded the Cubist movement.',
  },
  {
    id: 'faculty-arts-8',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Medium',
    prompt: 'What is the art of making three-dimensional objects called?',
    answers: ['Painting', 'Sculpture', 'Drawing', 'Printing'],
    correctIndex: 1,
    explanation: 'Sculpture is the art of creating three-dimensional objects.',
  },
  // ─── APTITUDE: More Logical Reasoning ─────────────────────
  {
    id: 'aptitude-11',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Medium',
    prompt: 'If all cats are animals and some animals are pets, which statement must be true?',
    answers: ['All cats are pets', 'Some cats are pets', 'Some animals are cats', 'No cats are pets'],
    correctIndex: 2,
    explanation: 'If all cats are animals, then at least some animals are cats when cats exist.',
  },
  {
    id: 'aptitude-12',
    category: 'aptitude',
    subject: 'Numerical Reasoning',
    difficulty: 'Hard',
    prompt: 'What is the next number in the sequence: 1, 1, 2, 3, 5, 8, ?',
    answers: ['11', '12', '13', '14'],
    correctIndex: 2,
    explanation: 'This is the Fibonacci sequence: each number is the sum of the two preceding ones. 5 + 8 = 13.',
  },
  {
    id: 'aptitude-13',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Easy',
    prompt: 'Which number comes next: 1, 3, 5, 7, ?',
    answers: ['8', '9', '10', '11'],
    correctIndex: 1,
    explanation: 'The sequence increases by 2 each time: 1, 3, 5, 7, 9.',
  },
  {
    id: 'aptitude-14',
    category: 'aptitude',
    subject: 'Verbal Reasoning',
    difficulty: 'Medium',
    prompt: 'Find the odd one out:',
    answers: ['Dog', 'Cat', 'Lion', 'Fish'],
    correctIndex: 3,
    explanation: 'Fish lives in water, while the others are land mammals.',
  },
  {
    id: 'aptitude-15',
    category: 'aptitude',
    subject: 'Numerical Reasoning',
    difficulty: 'Hard',
    prompt: 'What is 15% of 40% of 500?',
    answers: ['20', '30', '40', '50'],
    correctIndex: 1,
    explanation: '40% of 500 = 200. 15% of 200 = 30.',
  },
  {
    id: 'aptitude-16',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Medium',
    prompt: 'If you rearrange the letters "HRCMA", you get the name of a(n):',
    answers: ['City', 'Animal', 'Month', 'Country'],
    correctIndex: 2,
    explanation: 'Rearranging "HRCMA" gives "MARCH" which is a month.',
  },
  // ─── DAILY: More Mixed Questions ──────────────────────────
  {
    id: 'daily-maths-5',
    category: 'daily',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the value of 9 × 9?',
    answers: ['72', '81', '90', '99'],
    correctIndex: 1,
    explanation: '9 × 9 = 81.',
  },
  {
    id: 'daily-maths-6',
    category: 'daily',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 50 + 25?',
    answers: ['65', '70', '75', '80'],
    correctIndex: 2,
    explanation: '50 + 25 = 75.',
  },
  {
    id: 'daily-eng-5',
    category: 'daily',
    subject: 'English',
    difficulty: 'Medium',
    prompt: 'What is the past tense of "go"?',
    answers: ['Goed', 'Went', 'Gone', 'Going'],
    correctIndex: 1,
    explanation: 'The simple past tense of "go" is "went".',
  },
  {
    id: 'daily-eng-6',
    category: 'daily',
    subject: 'English',
    difficulty: 'Easy',
    prompt: 'Which word is an adverb?',
    answers: ['Quick', 'Quickly', 'Quickness', 'Quicken'],
    correctIndex: 1,
    explanation: '"Quickly" is an adverb modifying a verb, adjective, or other adverb.',
  },
  {
    id: 'daily-phys-4',
    category: 'daily',
    subject: 'Physics',
    difficulty: 'Medium',
    prompt: 'What is the unit of electric charge?',
    answers: ['Volt', 'Ampere', 'Coulomb', 'Ohm'],
    correctIndex: 2,
    explanation: 'Electric charge is measured in coulombs (C).',
  },
  {
    id: 'daily-chem-4',
    category: 'daily',
    subject: 'Chemistry',
    difficulty: 'Easy',
    prompt: 'What is the chemical symbol for oxygen?',
    answers: ['Ox', 'O', 'O₂', 'Om'],
    correctIndex: 1,
    explanation: 'The chemical symbol for oxygen is O.',
  },
  {
    id: 'daily-bio-4',
    category: 'daily',
    subject: 'Biology',
    difficulty: 'Medium',
    prompt: 'What is the main function of the lungs?',
    answers: ['Pump blood', 'Exchange oxygen and carbon dioxide', 'Digest food', 'Filter waste'],
    correctIndex: 1,
    explanation: 'The lungs are responsible for gas exchange.',
  },
  {
    id: 'daily-his-4',
    category: 'daily',
    subject: 'History',
    difficulty: 'Medium',
    prompt: 'Who was the first President of the United States?',
    answers: ['Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams'],
    correctIndex: 1,
    explanation: 'George Washington was the first President of the United States.',
  },
  {
    id: 'daily-geo-4',
    category: 'daily',
    subject: 'Geography',
    difficulty: 'Easy',
    prompt: 'What is the capital of the United States?',
    answers: ['New York', 'Washington D.C.', 'Los Angeles', 'Chicago'],
    correctIndex: 1,
    explanation: 'Washington D.C. is the capital of the United States.',
  },
  {
    id: 'daily-sport-4',
    category: 'daily',
    subject: 'Sports',
    difficulty: 'Medium',
    prompt: 'How many players are on a cricket team?',
    answers: ['9', '10', '11', '12'],
    correctIndex: 2,
    explanation: 'A cricket team has 11 players.',
  },
  {
    id: 'daily-tech-4',
    category: 'daily',
    subject: 'Technology',
    difficulty: 'Medium',
    prompt: 'What does "AI" stand for?',
    answers: ['Artificial Intelligence', 'Automated Input', 'Advanced Internet', 'Applied Information'],
    correctIndex: 0,
    explanation: 'AI stands for Artificial Intelligence.',
  },
  {
    id: 'daily-astro-4',
    category: 'daily',
    subject: 'Astronomy',
    difficulty: 'Medium',
    prompt: 'What is the largest planet in our solar system?',
    answers: ['Earth', 'Jupiter', 'Saturn', 'Neptune'],
    correctIndex: 1,
    explanation: 'Jupiter is the largest planet in our solar system.',
  },
  {
    id: 'daily-gk-4',
    category: 'daily',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'What is the largest mammal in the world?',
    answers: ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'],
    correctIndex: 1,
    explanation: 'The blue whale is the largest mammal in the world.',
  },
  {
    id: 'daily-gk-5',
    category: 'daily',
    subject: 'General Knowledge',
    difficulty: 'Medium',
    prompt: 'How many continents are there in the world?',
    answers: ['5', '6', '7', '8'],
    correctIndex: 2,
    explanation: 'There are 7 continents in the world.',
  },
  {
    id: 'daily-gk-6',
    category: 'daily',
    subject: 'General Knowledge',
    difficulty: 'Easy',
    prompt: 'What is the fastest land animal?',
    answers: ['Lion', 'Cheetah', 'Leopard', 'Horse'],
    correctIndex: 1,
    explanation: 'The cheetah is the fastest land animal, reaching speeds up to 120 km/h.',
  },
  // ─── DEPARTMENT: More Computer Science ────────────────────
  {
    id: 'dept-cs-15',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Medium',
    prompt: 'What is the output of 2 + 2 in JavaScript?',
    answers: ['22', '4', '2+2', 'Error'],
    correctIndex: 1,
    explanation: 'In JavaScript, 2 + 2 = 4.',
  },
  {
    id: 'dept-cs-16',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Hard',
    prompt: 'What is the difference between a compiler and an interpreter?',
    answers: ['No difference', 'Compiler translates entire program, interpreter translates line by line', 'Interpreter is faster', 'Compiler is for web only'],
    correctIndex: 1,
    explanation: 'A compiler translates the entire program at once, while an interpreter translates and executes line by line.',
  },
  {
    id: 'dept-cs-17',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Easy',
    prompt: 'What does "CSS" stand for?',
    answers: ['Cascading Style Sheets', 'Computer Style System', 'Creative Style Sheets', 'Cascading System Sheets'],
    correctIndex: 0,
    explanation: 'CSS stands for Cascading Style Sheets.',
  },
  {
    id: 'dept-cs-18',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Medium',
    prompt: 'What is the time complexity of linear search?',
    answers: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
    correctIndex: 2,
    explanation: 'Linear search has O(n) time complexity in the worst case.',
  },
  {
    id: 'dept-cs-19',
    category: 'department',
    subject: 'Programming',
    difficulty: 'Hard',
    prompt: 'What is the difference between "==" and "===" in JavaScript?',
    answers: ['No difference', '"==" compares values, "===" compares values and types', '"===" compares only types', '"==" is faster'],
    correctIndex: 1,
    explanation: '"==" performs type coercion, while "===" compares both value and type without coercion.',
  },
  {
    id: 'dept-cs-20',
    category: 'department',
    subject: 'Computer Science',
    difficulty: 'Easy',
    prompt: 'What is the full meaning of "URL"?',
    answers: ['Uniform Resource Locator', 'Universal Resource Link', 'Uniform Reference Locator', 'Universal Reference Link'],
    correctIndex: 0,
    explanation: 'URL stands for Uniform Resource Locator.',
  },
  // ─── DEPARTMENT: More Medicine ────────────────────────────
  {
    id: 'dept-med-13',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Medium',
    prompt: 'What is the smallest bone in the human body?',
    answers: ['Femur', 'Stapes', 'Tibia', 'Radius'],
    correctIndex: 1,
    explanation: 'The stapes (stirrup bone) in the ear is the smallest bone in the human body.',
  },
  {
    id: 'dept-med-14',
    category: 'department',
    subject: 'Physiology',
    difficulty: 'Easy',
    prompt: 'What is the normal resting heart rate for adults?',
    answers: ['40-60 bpm', '60-100 bpm', '100-140 bpm', '140-180 bpm'],
    correctIndex: 1,
    explanation: 'The normal resting heart rate for adults is 60-100 beats per minute.',
  },
  {
    id: 'dept-med-15',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Hard',
    prompt: 'How many pairs of ribs does the human body have?',
    answers: ['10', '12', '14', '16'],
    correctIndex: 1,
    explanation: 'The human body has 12 pairs of ribs.',
  },
  {
    id: 'dept-med-16',
    category: 'department',
    subject: 'Pharmacology',
    difficulty: 'Medium',
    prompt: 'What is the main function of antibiotics?',
    answers: ['Kill viruses', 'Kill bacteria', 'Reduce pain', 'Lower blood pressure'],
    correctIndex: 1,
    explanation: 'Antibiotics are used to treat bacterial infections.',
  },
  {
    id: 'dept-med-17',
    category: 'department',
    subject: 'Anatomy',
    difficulty: 'Easy',
    prompt: 'What is the main function of the lungs?',
    answers: ['Pump blood', 'Exchange oxygen and carbon dioxide', 'Digest food', 'Filter waste'],
    correctIndex: 1,
    explanation: 'The lungs are responsible for gas exchange.',
  },
  {
    id: 'dept-med-18',
    category: 'department',
    subject: 'Physiology',
    difficulty: 'Hard',
    prompt: 'What is the normal blood pressure reading for adults?',
    answers: ['80/60 mmHg', '120/80 mmHg', '160/100 mmHg', '200/120 mmHg'],
    correctIndex: 1,
    explanation: 'Normal blood pressure for adults is approximately 120/80 mmHg.',
  },
  // ─── DEPARTMENT: More Engineering ─────────────────────────
  {
    id: 'dept-eng-12',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Medium',
    prompt: 'What is the unit of electrical resistance?',
    answers: ['Volt', 'Ampere', 'Ohm', 'Watt'],
    correctIndex: 2,
    explanation: 'Electrical resistance is measured in ohms (Ω).',
  },
  {
    id: 'dept-eng-13',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Easy',
    prompt: 'What is the main material used in construction?',
    answers: ['Plastic', 'Concrete', 'Rubber', 'Glass'],
    correctIndex: 1,
    explanation: 'Concrete is the most widely used construction material.',
  },
  {
    id: 'dept-eng-14',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Hard',
    prompt: 'What is the difference between stress and strain?',
    answers: ['No difference', 'Stress is force per area, strain is deformation', 'Strain is force per area, stress is deformation', 'Both are the same'],
    correctIndex: 1,
    explanation: 'Stress is the force applied per unit area, while strain is the resulting deformation.',
  },
  {
    id: 'dept-eng-15',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Medium',
    prompt: 'What is the function of a transformer?',
    answers: ['Generate electricity', 'Change voltage levels', 'Store energy', 'Measure current'],
    correctIndex: 1,
    explanation: 'A transformer changes the voltage level of alternating current.',
  },
  {
    id: 'dept-eng-16',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Easy',
    prompt: 'What does "DC" stand for in electricity?',
    answers: ['Direct Current', 'Dynamic Current', 'Digital Current', 'Dual Current'],
    correctIndex: 0,
    explanation: 'DC stands for Direct Current, where electric charge flows in one direction.',
  },
  {
    id: 'dept-eng-17',
    category: 'department',
    subject: 'Engineering',
    difficulty: 'Hard',
    prompt: 'What is the second law of thermodynamics?',
    answers: ['Energy is conserved', 'Entropy always increases', 'Absolute zero is unattainable', 'Heat flows from cold to hot'],
    correctIndex: 1,
    explanation: 'The second law states that the total entropy of an isolated system always increases over time.',
  },
  // ─── DEPARTMENT: More Law ─────────────────────────────────
  {
    id: 'dept-law-9',
    category: 'department',
    subject: 'Law',
    difficulty: 'Medium',
    prompt: 'What is the difference between civil and criminal law?',
    answers: ['No difference', 'Civil law deals with disputes between individuals, criminal law deals with offenses against the state', 'Criminal law is always more serious', 'Civil law is for businesses only'],
    correctIndex: 1,
    explanation: 'Civil law resolves disputes between individuals, while criminal law deals with offenses against the state.',
  },
  {
    id: 'dept-law-10',
    category: 'department',
    subject: 'Law',
    difficulty: 'Easy',
    prompt: 'What is a contract?',
    answers: ['A type of crime', 'A legally binding agreement', 'A court judgment', 'A government policy'],
    correctIndex: 1,
    explanation: 'A contract is a legally binding agreement between two or more parties.',
  },
  {
    id: 'dept-law-11',
    category: 'department',
    subject: 'Law',
    difficulty: 'Hard',
    prompt: 'What is the difference between a tort and a crime?',
    answers: ['No difference', 'A tort is a civil wrong, a crime is an offense against the state', 'A crime is always more serious', 'A tort is for businesses only'],
    correctIndex: 1,
    explanation: 'A tort is a civil wrong that causes harm, while a crime is an offense against the state.',
  },
  {
    id: 'dept-law-12',
    category: 'department',
    subject: 'Law',
    difficulty: 'Medium',
    prompt: 'What is the burden of proof in criminal cases?',
    answers: ['Balance of probabilities', 'Beyond reasonable doubt', 'Preponderance of evidence', 'Clear and convincing evidence'],
    correctIndex: 1,
    explanation: 'In criminal cases, the prosecution must prove guilt beyond a reasonable doubt.',
  },
  // ─── DEPARTMENT: More Business / Commerce ────────────────
  {
    id: 'dept-com-9',
    category: 'department',
    subject: 'Business',
    difficulty: 'Medium',
    prompt: 'What is the difference between a sole proprietorship and a partnership?',
    answers: ['No difference', 'Sole proprietorship has one owner, partnership has two or more', 'Partnership is always larger', 'Sole proprietorship is illegal'],
    correctIndex: 1,
    explanation: 'A sole proprietorship is owned by one person, while a partnership is owned by two or more people.',
  },
  {
    id: 'dept-com-10',
    category: 'department',
    subject: 'Commerce',
    difficulty: 'Easy',
    prompt: 'What is the main purpose of a business?',
    answers: ['To lose money', 'To make a profit', 'To pay taxes', 'To hire workers'],
    correctIndex: 1,
    explanation: 'The main purpose of a business is to make a profit by providing goods or services.',
  },
  {
    id: 'dept-com-11',
    category: 'department',
    subject: 'Business',
    difficulty: 'Hard',
    prompt: 'What is the difference between a merger and an acquisition?',
    answers: ['No difference', 'Merger combines two companies, acquisition is one company buying another', 'Acquisition is always larger', 'Merger is illegal'],
    correctIndex: 1,
    explanation: 'A merger combines two companies into one, while an acquisition is one company purchasing another.',
  },
  {
    id: 'dept-com-12',
    category: 'department',
    subject: 'Commerce',
    difficulty: 'Medium',
    prompt: 'What is the function of a marketing department?',
    answers: ['Manufacture products', 'Promote and sell products', 'Manage finances', 'Hire employees'],
    correctIndex: 1,
    explanation: 'The marketing department promotes and sells products to customers.',
  },
  // ─── LEVEL: More Mathematics ──────────────────────────────
  {
    id: 'level-maths-11',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the value of 4³?',
    answers: ['16', '32', '64', '128'],
    correctIndex: 2,
    explanation: '4³ = 4 × 4 × 4 = 64.',
  },
  {
    id: 'level-maths-12',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Easy',
    prompt: 'What is 15 + 27?',
    answers: ['40', '42', '44', '46'],
    correctIndex: 1,
    explanation: '15 + 27 = 42.',
  },
  {
    id: 'level-maths-13',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Hard',
    prompt: 'What is the value of the limit as x→0 of (1 - cos x)/x²?',
    answers: ['0', '0.5', '1', '2'],
    correctIndex: 1,
    explanation: 'The limit of (1 - cos x)/x² as x approaches 0 is 1/2.',
  },
  {
    id: 'level-maths-14',
    category: 'level',
    subject: 'Mathematics',
    difficulty: 'Medium',
    prompt: 'What is the value of 2⁵?',
    answers: ['16', '32', '64', '128'],
    correctIndex: 1,
    explanation: '2⁵ = 2 × 2 × 2 × 2 × 2 = 32.',
  },
  // ─── LEVEL: More English ──────────────────────────────────
  {
    id: 'level-eng-9',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Medium',
    prompt: 'What is the correct plural of "child"?',
    answers: ['Childs', 'Childes', 'Children', 'Child\'s'],
    correctIndex: 2,
    explanation: '"Children" is the irregular plural form of "child".',
  },
  {
    id: 'level-eng-10',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Easy',
    prompt: 'Which word is a conjunction?',
    answers: ['Run', 'And', 'Quickly', 'Beautiful'],
    correctIndex: 1,
    explanation: '"And" is a conjunction that connects words or phrases.',
  },
  {
    id: 'level-eng-11',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Hard',
    prompt: 'What is the meaning of the word "ambiguous"?',
    answers: ['Clear', 'Having multiple meanings', 'Simple', 'Powerful'],
    correctIndex: 1,
    explanation: '"Ambiguous" means having more than one possible meaning or interpretation.',
  },
  {
    id: 'level-eng-12',
    category: 'level',
    subject: 'Use of English',
    difficulty: 'Medium',
    prompt: 'Choose the correct spelling:',
    answers: ['Definitely', 'Definately', 'Definitly', 'Definately'],
    correctIndex: 0,
    explanation: '"Definitely" is the correct spelling.',
  },
  // ─── LEVEL: More Science ──────────────────────────────────
  {
    id: 'level-sci-9',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the chemical symbol for hydrogen?',
    answers: ['H', 'He', 'Hy', 'Hd'],
    correctIndex: 0,
    explanation: 'Hydrogen\'s chemical symbol is H.',
  },
  {
    id: 'level-sci-10',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'What is the freezing point of water in Fahrenheit?',
    answers: ['0°F', '32°F', '100°F', '212°F'],
    correctIndex: 1,
    explanation: 'Water freezes at 32°F.',
  },
  {
    id: 'level-sci-11',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Hard',
    prompt: 'What is the speed of light in a vacuum?',
    answers: ['3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '3 × 10⁴ m/s'],
    correctIndex: 1,
    explanation: 'The speed of light in a vacuum is approximately 3 × 10⁸ m/s.',
  },
  {
    id: 'level-sci-12',
    category: 'level',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the chemical formula for table salt?',
    answers: ['KCl', 'NaCl', 'CaCl₂', 'MgCl₂'],
    correctIndex: 1,
    explanation: 'Table salt is sodium chloride (NaCl).',
  },
  // ─── FACULTY: More Engineering ────────────────────────────
  {
    id: 'faculty-eng-9',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Medium',
    prompt: 'What is the unit of electrical power?',
    answers: ['Volt', 'Ampere', 'Watt', 'Ohm'],
    correctIndex: 2,
    explanation: 'Electrical power is measured in watts (W).',
  },
  {
    id: 'faculty-eng-10',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Easy',
    prompt: 'Which of these is a non-renewable energy source?',
    answers: ['Solar', 'Wind', 'Coal', 'Hydroelectric'],
    correctIndex: 2,
    explanation: 'Coal is a non-renewable fossil fuel.',
  },
  {
    id: 'faculty-eng-11',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Hard',
    prompt: 'What is the formula for calculating power?',
    answers: ['P = VI', 'P = V/I', 'P = I/V', 'P = V + I'],
    correctIndex: 0,
    explanation: 'Power = Voltage × Current (P = VI).',
  },
  {
    id: 'faculty-eng-12',
    category: 'faculty',
    subject: 'General Engineering',
    difficulty: 'Medium',
    prompt: 'What is the main function of a generator?',
    answers: ['Store energy', 'Convert mechanical energy to electrical energy', 'Measure current', 'Change voltage'],
    correctIndex: 1,
    explanation: 'A generator converts mechanical energy into electrical energy.',
  },
  // ─── FACULTY: More Science ────────────────────────────────
  {
    id: 'faculty-sci-9',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the most abundant element in the universe?',
    answers: ['Oxygen', 'Hydrogen', 'Carbon', 'Helium'],
    correctIndex: 1,
    explanation: 'Hydrogen is the most abundant element in the universe.',
  },
  {
    id: 'faculty-sci-10',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Easy',
    prompt: 'What is the chemical symbol for nitrogen?',
    answers: ['N', 'Ni', 'Na', 'Ne'],
    correctIndex: 0,
    explanation: 'Nitrogen\'s chemical symbol is N.',
  },
  {
    id: 'faculty-sci-11',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Hard',
    prompt: 'What is the theory of evolution by natural selection attributed to?',
    answers: ['Isaac Newton', 'Charles Darwin', 'Albert Einstein', 'Gregor Mendel'],
    correctIndex: 1,
    explanation: 'Charles Darwin proposed the theory of evolution by natural selection.',
  },
  {
    id: 'faculty-sci-12',
    category: 'faculty',
    subject: 'General Science',
    difficulty: 'Medium',
    prompt: 'What is the main component of the Earth\'s core?',
    answers: ['Oxygen', 'Iron', 'Silicon', 'Carbon'],
    correctIndex: 1,
    explanation: 'The Earth\'s core is primarily composed of iron and nickel.',
  },
  // ─── FACULTY: More Arts ───────────────────────────────────
  {
    id: 'faculty-arts-9',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Medium',
    prompt: 'Who painted "The Starry Night"?',
    answers: ['Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dalí'],
    correctIndex: 1,
    explanation: 'Vincent van Gogh painted "The Starry Night".',
  },
  {
    id: 'faculty-arts-10',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Easy',
    prompt: 'What is the art of beautiful handwriting called?',
    answers: ['Origami', 'Calligraphy', 'Sculpture', 'Collage'],
    correctIndex: 1,
    explanation: 'Calligraphy is the art of beautiful handwriting.',
  },
  {
    id: 'faculty-arts-11',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Hard',
    prompt: 'Which art movement is Pablo Picasso associated with?',
    answers: ['Impressionism', 'Cubism', 'Surrealism', 'Realism'],
    correctIndex: 1,
    explanation: 'Pablo Picasso co-founded the Cubist movement.',
  },
  {
    id: 'faculty-arts-12',
    category: 'faculty',
    subject: 'Arts',
    difficulty: 'Medium',
    prompt: 'What is the art of making three-dimensional objects called?',
    answers: ['Painting', 'Sculpture', 'Drawing', 'Printing'],
    correctIndex: 1,
    explanation: 'Sculpture is the art of creating three-dimensional objects.',
  },
  // ─── APTITUDE: More Logical Reasoning ─────────────────────
  {
    id: 'aptitude-17',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Medium',
    prompt: 'If all cats are animals and some animals are pets, which statement must be true?',
    answers: ['All cats are pets', 'Some cats are pets', 'Some animals are cats', 'No cats are pets'],
    correctIndex: 2,
    explanation: 'If all cats are animals, then at least some animals are cats when cats exist.',
  },
  {
    id: 'aptitude-18',
    category: 'aptitude',
    subject: 'Numerical Reasoning',
    difficulty: 'Hard',
    prompt: 'What is the next number in the sequence: 1, 1, 2, 3, 5, 8, ?',
    answers: ['11', '12', '13', '14'],
    correctIndex: 2,
    explanation: 'This is the Fibonacci sequence: each number is the sum of the two preceding ones. 5 + 8 = 13.',
  },
  {
    id: 'aptitude-19',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Easy',
    prompt: 'Which number comes next: 1, 3, 5, 7, ?',
    answers: ['8', '9', '10', '11'],
    correctIndex: 1,
    explanation: 'The sequence increases by 2 each time: 1, 3, 5, 7, 9.',
  },
  {
    id: 'aptitude-20',
    category: 'aptitude',
    subject: 'Verbal Reasoning',
    difficulty: 'Medium',
    prompt: 'Find the odd one out:',
    answers: ['Dog', 'Cat', 'Lion', 'Fish'],
    correctIndex: 3,
    explanation: 'Fish lives in water, while the others are land mammals.',
  },
  {
    id: 'aptitude-21',
    category: 'aptitude',
    subject: 'Numerical Reasoning',
    difficulty: 'Hard',
    prompt: 'What is 15% of 40% of 500?',
    answers: ['20', '30', '40', '50'],
    correctIndex: 1,
    explanation: '40% of 500 = 200. 15% of 200 = 30.',
  },
  {
    id: 'aptitude-22',
    category: 'aptitude',
    subject: 'Logical Reasoning',
    difficulty: 'Medium',
    prompt: 'If you rearrange the letters "HRCMA", you get the name of a(n):',
    answers: ['City', 'Animal', 'Month', 'Country'],
    correctIndex: 2,
    explanation: 'Rearranging "HRCMA" gives "MARCH" which is a month.',
  },
];
export const getTodayKey = (date = new Date()) => date.toISOString().slice(0, 10);

export const getRankForXp = (xp = 0) => {
  if (xp >= 20000) return 'Legend';
  if (xp >= 12000) return 'Diamond';
  if (xp >= 7000) return 'Platinum';
  if (xp >= 3500) return 'Gold';
  if (xp >= 1200) return 'Silver';
  return 'Bronze';
};

export const calculateChallengeScore = ({ answers = [], durationSeconds = 0, totalQuestions = 1 }) => {
  const correct = answers.filter((item) => item.isCorrect).length;
  const wrong = answers.filter((item) => item.selectedIndex !== null && !item.isCorrect).length;
  const skipped = answers.filter((item) => item.selectedIndex === null).length;
  const accuracy = totalQuestions ? Math.round((correct / totalQuestions) * 100) : 0;
  const difficultyBonus = answers.reduce((sum, item) => {
    if (!item.isCorrect) return sum;
    if (item.difficulty === 'Hard') return sum + 8;
    if (item.difficulty === 'Medium') return sum + 5;
    return sum + 3;
  }, 0);
  const speedBonus = Math.max(0, 60 - Math.round(durationSeconds / Math.max(totalQuestions, 1)));
  const xpEarned = correct * 12 + difficultyBonus + Math.round(speedBonus / 2);
  const pointsEarned = correct * 100 + difficultyBonus * 5 + speedBonus;
  const isPerfect = correct === totalQuestions;

  return { correct, wrong, skipped, accuracy, xpEarned, pointsEarned, isPerfect };
};

export const buildCalendarDays = (daysBack = 120, activeDates = []) => {
  const activeSet = new Set(activeDates);
  return Array.from({ length: daysBack }).map((_, index) => {
    const date = new Date();
    date.setDate(date.getDate() - (daysBack - index - 1));
    const key = getTodayKey(date);
    return { key, day: date.getDate(), month: date.getMonth(), active: activeSet.has(key), isToday: key === getTodayKey() };
  });
};
