/**
 * Common departments found across Nigerian universities.
 * Used as fallback when Firestore departments collection is empty.
 */
export const COMMON_DEPARTMENTS = [
  { name: 'Computer Science', faculty: 'Science', universityId: 'any' },
  { name: 'Mathematics', faculty: 'Science', universityId: 'any' },
  { name: 'Physics', faculty: 'Science', universityId: 'any' },
  { name: 'Chemistry', faculty: 'Science', universityId: 'any' },
  { name: 'Biology', faculty: 'Science', universityId: 'any' },
  { name: 'Biochemistry', faculty: 'Science', universityId: 'any' },
  { name: 'Microbiology', faculty: 'Science', universityId: 'any' },
  { name: 'Geology', faculty: 'Science', universityId: 'any' },
  { name: 'Statistics', faculty: 'Science', universityId: 'any' },
  { name: 'Medicine & Surgery', faculty: 'Medical Sciences', universityId: 'any' },
  { name: 'Nursing Science', faculty: 'Medical Sciences', universityId: 'any' },
  { name: 'Pharmacy', faculty: 'Pharmacy', universityId: 'any' },
  { name: 'Medical Laboratory Science', faculty: 'Medical Sciences', universityId: 'any' },
  { name: 'Physiotherapy', faculty: 'Medical Sciences', universityId: 'any' },
  { name: 'Dentistry', faculty: 'Dental Sciences', universityId: 'any' },
  { name: 'Public Health', faculty: 'Medical Sciences', universityId: 'any' },
  { name: 'Law', faculty: 'Law', universityId: 'any' },
  { name: 'Mass Communication', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Economics', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Political Science', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Psychology', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Sociology', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Geography', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Philosophy', faculty: 'Arts', universityId: 'any' },
  { name: 'History & International Studies', faculty: 'Arts', universityId: 'any' },
  { name: 'English Language', faculty: 'Arts', universityId: 'any' },
  { name: 'Linguistics', faculty: 'Arts', universityId: 'any' },
  { name: 'Religious Studies', faculty: 'Arts', universityId: 'any' },
  { name: 'Theatre & Film Arts', faculty: 'Arts', universityId: 'any' },
  { name: 'Fine & Applied Arts', faculty: 'Arts', universityId: 'any' },
  { name: 'Accounting', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Business Administration', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Banking & Finance', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Marketing', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Public Administration', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Entrepreneurship', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Industrial Relations', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Civil Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Mechanical Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Electrical & Electronics Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Chemical Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Computer Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Agricultural Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Petroleum Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Biomedical Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Architecture', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Quantity Surveying', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Estate Management', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Urban & Regional Planning', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Building Technology', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Agriculture', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Agricultural Economics', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Animal Science', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Food Science & Technology', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Forestry & Wildlife Management', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Fisheries & Aquaculture', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Soil Science', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Education & Biology', faculty: 'Education', universityId: 'any' },
  { name: 'Education & Chemistry', faculty: 'Education', universityId: 'any' },
  { name: 'Education & Physics', faculty: 'Education', universityId: 'any' },
  { name: 'Education & Mathematics', faculty: 'Education', universityId: 'any' },
  { name: 'Education & English', faculty: 'Education', universityId: 'any' },
  { name: 'Education & Social Studies', faculty: 'Education', universityId: 'any' },
  { name: 'Guidance & Counselling', faculty: 'Education', universityId: 'any' },
  { name: 'Library & Information Science', faculty: 'Education', universityId: 'any' },
  { name: 'Human Kinetics & Health Education', faculty: 'Education', universityId: 'any' },
  { name: 'Veterinary Medicine', faculty: 'Veterinary Medicine', universityId: 'any' },
  { name: 'Nursing', faculty: 'Health Sciences', universityId: 'any' },
  { name: 'Radiography', faculty: 'Health Sciences', universityId: 'any' },
  { name: 'Anatomy', faculty: 'Basic Medical Sciences', universityId: 'any' },
  { name: 'Physiology', faculty: 'Basic Medical Sciences', universityId: 'any' },
  { name: 'Human Nutrition & Dietetics', faculty: 'Health Sciences', universityId: 'any' },
  { name: 'Optometry', faculty: 'Health Sciences', universityId: 'any' },
  { name: 'Health Information Management', faculty: 'Health Sciences', universityId: 'any' },
  { name: 'Community Health', faculty: 'Health Sciences', universityId: 'any' },
  { name: 'Cyber Security', faculty: 'Computing', universityId: 'any' },
  { name: 'Software Engineering', faculty: 'Computing', universityId: 'any' },
  { name: 'Information Technology', faculty: 'Computing', universityId: 'any' },
  { name: 'Information Systems', faculty: 'Computing', universityId: 'any' },
  { name: 'Data Science', faculty: 'Computing', universityId: 'any' },
  { name: 'Artificial Intelligence', faculty: 'Computing', universityId: 'any' },
  { name: 'Science Laboratory Technology', faculty: 'Science', universityId: 'any' },
  { name: 'Industrial Chemistry', faculty: 'Science', universityId: 'any' },
  { name: 'Industrial Mathematics', faculty: 'Science', universityId: 'any' },
  { name: 'Industrial Physics', faculty: 'Science', universityId: 'any' },
  { name: 'Environmental Biology', faculty: 'Science', universityId: 'any' },
  { name: 'Plant Science & Biotechnology', faculty: 'Science', universityId: 'any' },
  { name: 'Zoology', faculty: 'Science', universityId: 'any' },
  { name: 'Botany', faculty: 'Science', universityId: 'any' },
  { name: 'Computer Science Education', faculty: 'Education', universityId: 'any' },
  { name: 'Business Education', faculty: 'Education', universityId: 'any' },
  { name: 'Educational Management', faculty: 'Education', universityId: 'any' },
  { name: 'Early Childhood Education', faculty: 'Education', universityId: 'any' },
  { name: 'Adult Education', faculty: 'Education', universityId: 'any' },
  { name: 'Special Education', faculty: 'Education', universityId: 'any' },
  { name: 'Primary Education Studies', faculty: 'Education', universityId: 'any' },
  { name: 'French', faculty: 'Arts', universityId: 'any' },
  { name: 'Arabic Studies', faculty: 'Arts', universityId: 'any' },
  { name: 'Music', faculty: 'Arts', universityId: 'any' },
  { name: 'Creative Arts', faculty: 'Arts', universityId: 'any' },
  { name: 'Communication & Language Arts', faculty: 'Arts', universityId: 'any' },
  { name: 'Criminology & Security Studies', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Social Work', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'International Relations', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Peace & Conflict Studies', faculty: 'Social Sciences', universityId: 'any' },
  { name: 'Accountancy', faculty: 'Business', universityId: 'any' },
  { name: 'Business Administration & Management', faculty: 'Business', universityId: 'any' },
  { name: 'Office Technology & Management', faculty: 'Business', universityId: 'any' },
  { name: 'Insurance', faculty: 'Business', universityId: 'any' },
  { name: 'Taxation', faculty: 'Business', universityId: 'any' },
  { name: 'Human Resource Management', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Industrial Relations & Personnel Management', faculty: 'Management Sciences', universityId: 'any' },
  { name: 'Hospitality Management', faculty: 'Management', universityId: 'any' },
  { name: 'Leisure & Tourism Management', faculty: 'Management', universityId: 'any' },
  { name: 'Transport & Logistics Management', faculty: 'Management', universityId: 'any' },
  { name: 'Project Management', faculty: 'Management', universityId: 'any' },
  { name: 'Mechatronics Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Metallurgical & Materials Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Marine Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Mining Engineering', faculty: 'Engineering', universityId: 'any' },
  { name: 'Welding & Fabrication', faculty: 'Engineering', universityId: 'any' },
  { name: 'Petroleum Engineering & Gas Processing', faculty: 'Engineering', universityId: 'any' },
  { name: 'Surveying & Geo-informatics', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Environmental Management', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Environmental Health Technology', faculty: 'Environmental Sciences', universityId: 'any' },
  { name: 'Horticulture', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Crop Science', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Agronomy', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Home Economics', faculty: 'Agriculture', universityId: 'any' },
  { name: 'Common & Islamic Law', faculty: 'Law', universityId: 'any' },
  { name: 'Sharia Law', faculty: 'Law', universityId: 'any' },
];
