const inferType = (school) => {
  const n = school.name.toLowerCase();
  if (n.includes('polytechnic')) return 'polytechnic';
  if (n.includes('college')) return 'college';
  return 'university';
};

const TYPE_OVERRIDES = {
  'Yaba College of Technology': 'polytechnic',
  'Ogun State Institute of Technology, Igbesa': 'polytechnic',
  'Institute of Management and Technology, Enugu': 'polytechnic',
};

export const NIGERIA_UNIVERSITIES = [
  { name: 'University of Ibadan', shortName: 'UI', state: 'Oyo', country: 'Nigeria' },
  { name: 'University of Lagos', shortName: 'UNILAG', state: 'Lagos', country: 'Nigeria' },
  { name: 'Obafemi Awolowo University', shortName: 'OAU', state: 'Osun', country: 'Nigeria' },
  { name: 'University of Nigeria, Nsukka', shortName: 'UNN', state: 'Enugu', country: 'Nigeria' },
  { name: 'Ahmadu Bello University', shortName: 'ABU', state: 'Kaduna', country: 'Nigeria' },
  { name: 'University of Benin', shortName: 'UNIBEN', state: 'Edo', country: 'Nigeria' },
  { name: 'University of Ilorin', shortName: 'UNILORIN', state: 'Kwara', country: 'Nigeria' },
  { name: 'University of Calabar', shortName: 'UNICAL', state: 'Cross River', country: 'Nigeria' },
  { name: 'Lagos State University', shortName: 'LASU', state: 'Lagos', country: 'Nigeria' },
  { name: 'University of Port Harcourt', shortName: 'UNIPORT', state: 'Rivers', country: 'Nigeria' },
  { name: 'Federal University of Technology, Akure', shortName: 'FUTA', state: 'Ondo', country: 'Nigeria' },
  { name: 'Federal University of Technology, Owerri', shortName: 'FUTO', state: 'Imo', country: 'Nigeria' },
  { name: 'Federal University of Technology, Minna', shortName: 'FUTMINNA', state: 'Niger', country: 'Nigeria' },
  { name: 'Nnamdi Azikiwe University', shortName: 'UNIZIK', state: 'Anambra', country: 'Nigeria' },
  { name: 'University of Uyo', shortName: 'UNIUYO', state: 'Akwa Ibom', country: 'Nigeria' },
  { name: 'University of Jos', shortName: 'UNIJOS', state: 'Plateau', country: 'Nigeria' },
  { name: 'University of Maiduguri', shortName: 'UNIMAID', state: 'Borno', country: 'Nigeria' },
  { name: 'Bayero University, Kano', shortName: 'BUK', state: 'Kano', country: 'Nigeria' },
  { name: 'University of Abuja', shortName: 'UNIABUJA', state: 'FCT', country: 'Nigeria' },
  { name: 'Michael Okpara University of Agriculture', shortName: 'MOUAU', state: 'Abia', country: 'Nigeria' },
  { name: 'Federal University of Agriculture, Abeokuta', shortName: 'FUNAAB', state: 'Ogun', country: 'Nigeria' },
  { name: 'Ladoke Akintola University of Technology', shortName: 'LAUTECH', state: 'Oyo', country: 'Nigeria' },
  { name: 'Enugu State University of Science and Technology', shortName: 'ESUT', state: 'Enugu', country: 'Nigeria' },
  { name: 'Rivers State University', shortName: 'RSU', state: 'Rivers', country: 'Nigeria' },
  { name: 'Delta State University, Abraka', shortName: 'DELSU', state: 'Delta', country: 'Nigeria' },
  { name: 'Ekiti State University', shortName: 'EKSU', state: 'Ekiti', country: 'Nigeria' },
  { name: 'Kogi State University', shortName: 'KSU', state: 'Kogi', country: 'Nigeria' },
  { name: 'Olabisi Onabanjo University', shortName: 'OOU', state: 'Ogun', country: 'Nigeria' },
  { name: 'Osun State University', shortName: 'UNIOSUN', state: 'Osun', country: 'Nigeria' },
  { name: 'Covenant University', shortName: 'Covenant', state: 'Ogun', country: 'Nigeria' },
  { name: 'Babcock University', shortName: 'Babcock', state: 'Ogun', country: 'Nigeria' },
  { name: 'Bowen University', shortName: 'Bowen', state: 'Osun', country: 'Nigeria' },
  { name: 'Pan-Atlantic University', shortName: 'PAU', state: 'Lagos', country: 'Nigeria' },
  { name: "Redeemer's University", shortName: 'RUN', state: 'Osun', country: 'Nigeria' },
  { name: 'Nile University of Nigeria', shortName: 'Nile', state: 'FCT', country: 'Nigeria' },
  { name: 'Baze University', shortName: 'Baze', state: 'FCT', country: 'Nigeria' },
  { name: 'Federal University, Oye-Ekiti', shortName: 'FUOYE', state: 'Ekiti', country: 'Nigeria' },
  { name: 'Federal University, Lokoja', shortName: 'FUL', state: 'Kogi', country: 'Nigeria' },
  { name: 'Federal University, Dutse', shortName: 'FUD', state: 'Jigawa', country: 'Nigeria' },
  { name: 'Federal University, Wukari', shortName: 'FUWUKARI', state: 'Taraba', country: 'Nigeria' },
  { name: 'Federal University, Lafia', shortName: 'FULAFIA', state: 'Nasarawa', country: 'Nigeria' },
  { name: 'Kwara State University, Malete', shortName: 'KWASU', state: 'Kwara', country: 'Nigeria' },
  { name: 'Nasarawa State University, Keffi', shortName: 'NSUK', state: 'Nasarawa', country: 'Nigeria' },
  { name: 'Kaduna State University', shortName: 'KASU', state: 'Kaduna', country: 'Nigeria' },
  { name: 'Benue State University, Makurdi', shortName: 'BSUM', state: 'Benue', country: 'Nigeria' },
  { name: 'Gombe State University', shortName: 'GSU', state: 'Gombe', country: 'Nigeria' },
  { name: 'Adamawa State University', shortName: 'ADSU', state: 'Adamawa', country: 'Nigeria' },
  { name: 'Usmanu Danfodiyo University, Sokoto', shortName: 'UDUSOK', state: 'Sokoto', country: 'Nigeria' },
  { name: 'Abubakar Tafawa Balewa University, Bauchi', shortName: 'ATBU', state: 'Bauchi', country: 'Nigeria' },
  { name: 'Modibbo Adama University, Yola', shortName: 'MAU', state: 'Adamawa', country: 'Nigeria' },
  { name: 'University of Medical Sciences, Ondo', shortName: 'UNIMED', state: 'Ondo', country: 'Nigeria' },
  { name: 'Federal University, Gashua', shortName: 'FUGASHUA', state: 'Yobe', country: 'Nigeria' },
  { name: 'Federal University, Kashere', shortName: 'FUK', state: 'Gombe', country: 'Nigeria' },
  { name: 'Federal University, Birnin Kebbi', shortName: 'FUBK', state: 'Kebbi', country: 'Nigeria' },
  { name: 'Federal University, Gusau', shortName: 'FUGUS', state: 'Zamfara', country: 'Nigeria' },
  { name: 'Yobe State University', shortName: 'YSU', state: 'Yobe', country: 'Nigeria' },
  { name: 'Taraba State University', shortName: 'TSU', state: 'Taraba', country: 'Nigeria' },
  { name: 'Plateau State University', shortName: 'PLASU', state: 'Plateau', country: 'Nigeria' },
  { name: 'Ondo State University of Science and Technology', shortName: 'OSUSTECH', state: 'Ondo', country: 'Nigeria' },
  { name: 'Sokoto State University', shortName: 'SSU', state: 'Sokoto', country: 'Nigeria' },
  { name: 'Ebonyi State University', shortName: 'EBSU', state: 'Ebonyi', country: 'Nigeria' },
  { name: 'Ignatius Ajuru University of Education', shortName: 'IAUE', state: 'Rivers', country: 'Nigeria' },
  { name: 'Tai Solarin University of Education', shortName: 'TASUED', state: 'Ogun', country: 'Nigeria' },
  { name: 'Imo State University', shortName: 'IMSU', state: 'Imo', country: 'Nigeria' },
  { name: 'Abia State University, Uturu', shortName: 'ABSU', state: 'Abia', country: 'Nigeria' },
  { name: 'Chukwuemeka Odumegwu Ojukwu University', shortName: 'COOU', state: 'Anambra', country: 'Nigeria' },
  { name: 'Bingham University', shortName: 'Bingham', state: 'Nasarawa', country: 'Nigeria' },
  { name: 'Landmark University', shortName: 'Landmark', state: 'Kwara', country: 'Nigeria' },
  { name: 'Lead City University', shortName: 'LCU', state: 'Oyo', country: 'Nigeria' },
  { name: 'Madonna University', shortName: 'Madonna', state: 'Anambra', country: 'Nigeria' },
  { name: 'Ajayi Crowther University', shortName: 'ACU', state: 'Oyo', country: 'Nigeria' },
  { name: 'American University of Nigeria', shortName: 'AUN', state: 'Adamawa', country: 'Nigeria' },
  { name: 'Augustine University', shortName: 'AUI', state: 'Lagos', country: 'Nigeria' },
  { name: 'Chrisland University', shortName: 'Chrisland', state: 'Ogun', country: 'Nigeria' },
  { name: 'Crawford University', shortName: 'Crawford', state: 'Ogun', country: 'Nigeria' },
  { name: 'Dominican University', shortName: 'Dominican', state: 'Oyo', country: 'Nigeria' },
  { name: 'Elizade University', shortName: 'Elizade', state: 'Ondo', country: 'Nigeria' },
  { name: 'Fountain University', shortName: 'Fountain', state: 'Osun', country: 'Nigeria' },
  { name: 'Godfrey Okoye University', shortName: 'GOU', state: 'Enugu', country: 'Nigeria' },
  { name: 'Gregory University', shortName: 'GUU', state: 'Abia', country: 'Nigeria' },
  { name: 'Hallmark University', shortName: 'Hallmark', state: 'Ogun', country: 'Nigeria' },
  { name: 'Hezekiah University', shortName: 'Hezekiah', state: 'Imo', country: 'Nigeria' },
  { name: 'Joseph Ayo Babalola University', shortName: 'JABU', state: 'Osun', country: 'Nigeria' },
  { name: 'Kings University', shortName: 'Kings', state: 'Osun', country: 'Nigeria' },
  { name: 'Mountain Top University', shortName: 'MTU', state: 'Ogun', country: 'Nigeria' },
  { name: 'Novena University', shortName: 'Novena', state: 'Delta', country: 'Nigeria' },
  { name: 'Obong University', shortName: 'Obong', state: 'Akwa Ibom', country: 'Nigeria' },
  { name: 'Oduduwa University', shortName: 'Oduduwa', state: 'Osun', country: 'Nigeria' },
  { name: 'Paul University', shortName: 'Paul', state: 'Anambra', country: 'Nigeria' },
  { name: 'Rhema University', shortName: 'Rhema', state: 'Abia', country: 'Nigeria' },
  { name: 'Ritman University', shortName: 'Ritman', state: 'Akwa Ibom', country: 'Nigeria' },
  { name: 'Salem University', shortName: 'Salem', state: 'Kogi', country: 'Nigeria' },
  { name: 'Samuel Adegboyega University', shortName: 'SAU', state: 'Edo', country: 'Nigeria' },
  { name: 'Southwestern University', shortName: 'SWU', state: 'Ogun', country: 'Nigeria' },
  { name: 'Summit University', shortName: 'Summit', state: 'Kwara', country: 'Nigeria' },
  { name: 'Trinity University', shortName: 'Trinity', state: 'Oyo', country: 'Nigeria' },
  { name: 'Topfaith University', shortName: 'Topfaith', state: 'Akwa Ibom', country: 'Nigeria' },
  { name: 'Adeleke University', shortName: 'Adeleke', state: 'Osun', country: 'Nigeria' },
  { name: 'Afe Babalola University', shortName: 'ABUAD', state: 'Ekiti', country: 'Nigeria' },
  { name: 'Al-Hikmah University', shortName: 'Al-Hikmah', state: 'Kwara', country: 'Nigeria' },
  { name: 'Anchor University', shortName: 'Anchor', state: 'Lagos', country: 'Nigeria' },
  { name: 'Coal City University', shortName: 'CCU', state: 'Enugu', country: 'Nigeria' },
  { name: 'Clifford University', shortName: 'Clifford', state: 'Abia', country: 'Nigeria' },
  { name: 'McPherson University', shortName: 'McPherson', state: 'Ogun', country: 'Nigeria' },
  { name: 'Skyline University Nigeria', shortName: 'SUN', state: 'Kano', country: 'Nigeria' },
  { name: 'Spiritan University, Nneochi', shortName: 'SUN', state: 'Abia', country: 'Nigeria' },
  { name: 'St. Augustine\'s University', shortName: 'SAU', state: 'Lagos', country: 'Nigeria' },
  { name: 'Veritas University', shortName: 'Veritas', state: 'FCT', country: 'Nigeria' },
  { name: 'Wellspring University', shortName: 'Wellspring', state: 'Edo', country: 'Nigeria' },
  { name: 'Wesley University, Ondo', shortName: 'Wesley', state: 'Ondo', country: 'Nigeria' },
  { name: 'Western Delta University', shortName: 'WDU', state: 'Delta', country: 'Nigeria' },
  { name: 'Kwararafa University', shortName: 'Kwararafa', state: 'Taraba', country: 'Nigeria' },
  { name: 'Micheal and Cecilia Ibru University', shortName: 'MCIU', state: 'Delta', country: 'Nigeria' },
  { name: 'Nigerian Turkish Nile University', shortName: 'NTNU', state: 'FCT', country: 'Nigeria' },
  { name: 'University of Mkar', shortName: 'UniMkar', state: 'Benue', country: 'Nigeria' },
  { name: 'Benson Idahosa University', shortName: 'BIU', state: 'Edo', country: 'Nigeria' },
  { name: 'Igbinedion University, Okada', shortName: 'IUO', state: 'Edo', country: 'Nigeria' },
  { name: 'Caleb University', shortName: 'Caleb', state: 'Lagos', country: 'Nigeria' },
  { name: 'Caritas University', shortName: 'Caritas', state: 'Enugu', country: 'Nigeria' },
  { name: 'Delta State University of Science and Technology, Ozoro', shortName: 'DSUST', state: 'Delta', country: 'Nigeria' },
  { name: 'Edo State University, Uzairue', shortName: 'EDSU', state: 'Edo', country: 'Nigeria' },
  { name: 'University of Africa, Toru-Orua', shortName: 'UAT', state: 'Bayelsa', country: 'Nigeria' },
  { name: 'Niger Delta University', shortName: 'NDU', state: 'Bayelsa', country: 'Nigeria' },
  { name: 'Federal University of Petroleum Resources, Effurun', shortName: 'FUPRE', state: 'Delta', country: 'Nigeria' },
  { name: 'Maritime University, Okerenkoko', shortName: 'MUO', state: 'Delta', country: 'Nigeria' },
  { name: 'Bayelsa Medical University', shortName: 'BMU', state: 'Bayelsa', country: 'Nigeria' },
  { name: 'Sule Lamido University, Kafin Hausa', shortName: 'SLU', state: 'Jigawa', country: 'Nigeria' },
  { name: 'Yusuf Maitama Sule University, Kano', shortName: 'YUMSUK', state: 'Kano', country: 'Nigeria' },
  { name: 'Sa\'adu Zungur University', shortName: 'SAZU', state: 'Bauchi', country: 'Nigeria' },
  { name: 'Hassan Usman Katsina University', shortName: 'HUK', state: 'Katsina', country: 'Nigeria' },
  { name: 'Umaru Musa Yar\'adua University', shortName: 'UMYU', state: 'Katsina', country: 'Nigeria' },
  { name: 'Al-Qalam University, Katsina', shortName: 'AUK', state: 'Katsina', country: 'Nigeria' },
  { name: 'Khadija University, Majia', shortName: 'KUM', state: 'Jigawa', country: 'Nigeria' },
  { name: 'Federal University, Kafin Hausa', shortName: 'FUKH', state: 'Jigawa', country: 'Nigeria' },
  { name: 'Tasmanian University of Science and Technology', shortName: 'TUST', state: 'Anambra', country: 'Nigeria' },
  { name: 'Anambra State University', shortName: 'ANSU', state: 'Anambra', country: 'Nigeria' },
  { name: 'University of Delta, Agbor', shortName: 'UNIDEL', state: 'Delta', country: 'Nigeria' },
  { name: 'University of Agriculture and Environmental Sciences, Umuagwo', shortName: 'UAES', state: 'Imo', country: 'Nigeria' },
  { name: 'Kebbi State University of Science and Technology', shortName: 'KSUSTA', state: 'Kebbi', country: 'Nigeria' },
  { name: 'Zamfara State University', shortName: 'ZSU', state: 'Zamfara', country: 'Nigeria' },
  { name: 'Nigerian Army University, Biu', shortName: 'NAUB', state: 'Borno', country: 'Nigeria' },
  { name: 'Air Force Institute of Technology', shortName: 'AFIT', state: 'Kaduna', country: 'Nigeria' },
  { name: 'Nigerian Defence Academy', shortName: 'NDA', state: 'Kaduna', country: 'Nigeria' },
  { name: 'Federal College of Education (Technical), Akoka', shortName: 'FCET-Akoka', state: 'Lagos', country: 'Nigeria' },
  { name: 'Federal College of Education (Technical), Gombe', shortName: 'FCET-Gombe', state: 'Gombe', country: 'Nigeria' },
  { name: 'Federal College of Education (Technical), Potiskum', shortName: 'FCET-Potiskum', state: 'Yobe', country: 'Nigeria' },
  { name: 'National Open University of Nigeria', shortName: 'NOUN', state: 'Lagos', country: 'Nigeria' },
  { name: 'Yaba College of Technology', shortName: 'YABATECH', state: 'Lagos', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ilaro', shortName: 'Ilaro Poly', state: 'Ogun', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Nekede', shortName: 'Nekede Poly', state: 'Imo', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Bauchi', shortName: 'Bauchi Poly', state: 'Bauchi', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Oko', shortName: 'Oko Poly', state: 'Anambra', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Bida', shortName: 'Bida Poly', state: 'Niger', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Kaduna', shortName: 'Kaduna Poly', state: 'Kaduna', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Offa', shortName: 'Offa Poly', state: 'Kwara', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ede', shortName: 'Ede Poly', state: 'Osun', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ado-Ekiti', shortName: 'Ado Poly', state: 'Ekiti', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Damaturu', shortName: 'Damaturu Poly', state: 'Yobe', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Mubi', shortName: 'Mubi Poly', state: 'Adamawa', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Nasarawa', shortName: 'Nasarawa Poly', state: 'Nasarawa', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Bali', shortName: 'Bali Poly', state: 'Taraba', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Kaura Namoda', shortName: 'Kaura Poly', state: 'Zamfara', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ugep', shortName: 'Ugep Poly', state: 'Cross River', country: 'Nigeria' },
  { name: 'Lagos City Polytechnic', shortName: 'LCP', state: 'Lagos', country: 'Nigeria' },
  { name: 'Lagos State Polytechnic', shortName: 'LASPOTECH', state: 'Lagos', country: 'Nigeria' },
  { name: 'Moshood Abiola Polytechnic', shortName: 'MAPOLY', state: 'Ogun', country: 'Nigeria' },
  { name: 'The Polytechnic, Ibadan', shortName: 'Poly Ibadan', state: 'Oyo', country: 'Nigeria' },
  { name: 'Rufus Giwa Polytechnic, Owo', shortName: 'RUGIPO', state: 'Ondo', country: 'Nigeria' },
  { name: 'Auchi Polytechnic, Auchi', shortName: 'Auchi Poly', state: 'Edo', country: 'Nigeria' },
  { name: 'Kano State Polytechnic', shortName: 'Kano Poly', state: 'Kano', country: 'Nigeria' },
  { name: 'Kaduna Polytechnic', shortName: 'KadPoly', state: 'Kaduna', country: 'Nigeria' },
  { name: 'Hussaini Adamu Federal Polytechnic', shortName: 'HAFPOLY', state: 'Jigawa', country: 'Nigeria' },
  { name: 'Jigawa State Polytechnic', shortName: 'Jigawa Poly', state: 'Jigawa', country: 'Nigeria' },
  { name: 'Nuhu Bamalli Polytechnic', shortName: 'NUBAPOLY', state: 'Kaduna', country: 'Nigeria' },
  { name: 'Delta State Polytechnic, Ogwashi-Uku', shortName: 'DSPG', state: 'Delta', country: 'Nigeria' },
  { name: 'Delta State Polytechnic, Otefe-Oghara', shortName: 'DSOP', state: 'Delta', country: 'Nigeria' },
  { name: 'Delta State Polytechnic, Ozoro', shortName: 'DSO', state: 'Delta', country: 'Nigeria' },
  { name: 'Imo State Polytechnic', shortName: 'IMOPOLY', state: 'Imo', country: 'Nigeria' },
  { name: 'Institute of Management and Technology, Enugu', shortName: 'IMT', state: 'Enugu', country: 'Nigeria' },
  { name: 'Akwa Ibom State Polytechnic', shortName: 'AKIPOLY', state: 'Akwa Ibom', country: 'Nigeria' },
  { name: 'Cross River State Polytechnic', shortName: 'CRSPOLY', state: 'Cross River', country: 'Nigeria' },
  { name: 'Plateau State Polytechnic', shortName: 'PLAPOLY', state: 'Plateau', country: 'Nigeria' },
  { name: 'Benue State Polytechnic, Ugbokolo', shortName: 'BENPOLY', state: 'Benue', country: 'Nigeria' },
  { name: 'Abia State Polytechnic', shortName: 'ABIAPOLY', state: 'Abia', country: 'Nigeria' },
  { name: 'Edo State Polytechnic, Usen', shortName: 'EDOPOLY', state: 'Edo', country: 'Nigeria' },
  { name: 'Kwara State Polytechnic', shortName: 'KWAPOLY', state: 'Kwara', country: 'Nigeria' },
  { name: 'Osun State Polytechnic, Iree', shortName: 'OSPOLY', state: 'Osun', country: 'Nigeria' },
  { name: 'Ogun State Institute of Technology, Igbesa', shortName: 'OGITECH', state: 'Ogun', country: 'Nigeria' },
  { name: 'Ramat Polytechnic, Maiduguri', shortName: 'Ramat Poly', state: 'Borno', country: 'Nigeria' },
  { name: 'Waziri Umaru Federal Polytechnic', shortName: 'WUFP', state: 'Kebbi', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ukana', shortName: 'Ukana Poly', state: 'Akwa Ibom', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ekowe', shortName: 'Ekowe Poly', state: 'Bayelsa', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Idah', shortName: 'Idah Poly', state: 'Kogi', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Daura', shortName: 'Daura Poly', state: 'Katsina', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Monguno', shortName: 'Monguno Poly', state: 'Borno', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Orogun', shortName: 'Orogun Poly', state: 'Delta', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ayede', shortName: 'Ayede Poly', state: 'Oyo', country: 'Nigeria' },
  { name: 'Federal Polytechnic, Ohodo', shortName: 'Ohodo Poly', state: 'Enugu', country: 'Nigeria' },
  { name: 'Niger State Polytechnic, Zungeru', shortName: 'Niger Poly', state: 'Niger', country: 'Nigeria' },
  { name: 'Kogi State Polytechnic, Lokoja', shortName: 'Kogi Poly', state: 'Kogi', country: 'Nigeria' },
  { name: 'Taraba State Polytechnic, Jalingo', shortName: 'Taraba Poly', state: 'Taraba', country: 'Nigeria' },
  { name: 'Yobe State Polytechnic, Geidam', shortName: 'Yobe Poly', state: 'Yobe', country: 'Nigeria' },
  { name: 'Gombe State Polytechnic, Bajoga', shortName: 'Gombe Poly', state: 'Gombe', country: 'Nigeria' },
  { name: 'Federal College of Education, Abeokuta', shortName: 'FCE Abeokuta', state: 'Ogun', country: 'Nigeria' },
  { name: 'Federal College of Education, Zaria', shortName: 'FCE Zaria', state: 'Kaduna', country: 'Nigeria' },
  { name: 'Federal College of Education, Osiele', shortName: 'FCE Osiele', state: 'Ogun', country: 'Nigeria' },
  { name: 'Federal College of Education, Kano', shortName: 'FCE Kano', state: 'Kano', country: 'Nigeria' },
  { name: 'Federal College of Education, Yola', shortName: 'FCE Yola', state: 'Adamawa', country: 'Nigeria' },
  { name: 'Federal College of Education, Pankshin', shortName: 'FCE Pankshin', state: 'Plateau', country: 'Nigeria' },
  { name: 'Federal College of Education, Okene', shortName: 'FCE Okene', state: 'Kogi', country: 'Nigeria' },
  { name: 'Federal College of Education, Umunze', shortName: 'FCE Umunze', state: 'Anambra', country: 'Nigeria' },
  { name: 'Federal College of Education, Obudu', shortName: 'FCE Obudu', state: 'Cross River', country: 'Nigeria' },
  { name: 'Federal College of Education, Eha-Amufu', shortName: 'FCE Eha-Amufu', state: 'Enugu', country: 'Nigeria' },
  { name: 'Federal College of Education, Kontagora', shortName: 'FCE Kontagora', state: 'Niger', country: 'Nigeria' },
  { name: 'Federal College of Education, Katsina', shortName: 'FCE Katsina', state: 'Katsina', country: 'Nigeria' },
  { name: 'Federal College of Education, Potiskum', shortName: 'FCE Potiskum', state: 'Yobe', country: 'Nigeria' },
  { name: 'Adeniran Ogunsanya College of Education', shortName: 'AOCOED', state: 'Lagos', country: 'Nigeria' },
  { name: 'Alvan Ikoku Federal University of Education', shortName: 'Alvan Ikoku', state: 'Imo', country: 'Nigeria' },
  { name: 'Tai Solarin College of Education, Omu-Ijebu', shortName: 'TASCE', state: 'Ogun', country: 'Nigeria' },
  { name: 'Oyo State College of Education, Oyo', shortName: 'OYSCED', state: 'Oyo', country: 'Nigeria' },
  { name: 'Edo State College of Education, Igueben', shortName: 'ESCOE', state: 'Edo', country: 'Nigeria' },
  { name: 'Kwara State College of Education, Ilorin', shortName: 'KWCOE', state: 'Kwara', country: 'Nigeria' },
  { name: 'Osun State College of Education, Ila-Orangun', shortName: 'OSCOE', state: 'Osun', country: 'Nigeria' },
  { name: 'Delta State College of Education, Agbor', shortName: 'DSCOE', state: 'Delta', country: 'Nigeria' },
  { name: 'Rivers State College of Education', shortName: 'RSCOE', state: 'Rivers', country: 'Nigeria' },
  { name: 'College of Education, Akwanga', shortName: 'COE Akwanga', state: 'Nasarawa', country: 'Nigeria' },
  { name: 'College of Education, Gindiri', shortName: 'COE Gindiri', state: 'Plateau', country: 'Nigeria' },
  { name: 'College of Education, Jalingo', shortName: 'COE Jalingo', state: 'Taraba', country: 'Nigeria' },
  { name: 'College of Education, Katsina-Ala', shortName: 'COE Katsina-Ala', state: 'Benue', country: 'Nigeria' },
  { name: 'College of Education, Oro', shortName: 'COE Oro', state: 'Kwara', country: 'Nigeria' },
  { name: 'Nwafor Orizu College of Education, Nsugbe', shortName: 'NOCOE', state: 'Anambra', country: 'Nigeria' },
  { name: 'Imo State College of Education', shortName: 'IMSCOE', state: 'Imo', country: 'Nigeria' },
  { name: 'Kogi State College of Education, Ankpa', shortName: 'KSCOE', state: 'Kogi', country: 'Nigeria' },
  { name: 'Kogi State College of Education, Kabba', shortName: 'KSCOE Kabba', state: 'Kogi', country: 'Nigeria' },
  { name: 'Bauchi State College of Education', shortName: 'BASCOE', state: 'Bauchi', country: 'Nigeria' },
  { name: 'Gombe State College of Education', shortName: 'GOMSCOE', state: 'Gombe', country: 'Nigeria' },
  { name: 'Kano State College of Education', shortName: 'KSCOE Kano', state: 'Kano', country: 'Nigeria' },
  { name: 'Katsina State College of Education', shortName: 'KTSCOE', state: 'Katsina', country: 'Nigeria' },
  { name: 'Niger State College of Education', shortName: 'NSCOE', state: 'Niger', country: 'Nigeria' },
  { name: 'Sokoto State College of Education', shortName: 'SSCOE', state: 'Sokoto', country: 'Nigeria' },
  { name: 'College of Education, Azare', shortName: 'COE Azare', state: 'Bauchi', country: 'Nigeria' },
  { name: 'College of Education, Hong', shortName: 'COE Hong', state: 'Adamawa', country: 'Nigeria' },
  { name: 'College of Education, Maru', shortName: 'COE Maru', state: 'Zamfara', country: 'Nigeria' },
  { name: 'Enugu State College of Education (Technical)', shortName: 'ESCET', state: 'Enugu', country: 'Nigeria' },
].map((u) => ({ ...u, type: TYPE_OVERRIDES[u.name] || inferType(u) }));
